#!/usr/bin/env python
#coding=utf-8

import os
import sys
import subprocess
import platform
import urllib
import zipfile
import time
import re
import argparse
import shlex
import gzip

#=======================================================================================================================
#           Project paths
#=======================================================================================================================
#project
PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
CONTRIB_PATH = os.path.join(PROJECT_PATH, 'contrib')
SRC_PATH = os.path.join(PROJECT_PATH, 'src')
OUT_PATH = os.path.join(PROJECT_PATH, 'out')
CSS_PATH = os.path.join(PROJECT_PATH, 'css', 'anychart.css')
MODULES_PATH = os.path.join(SRC_PATH, 'modules')
THEMES_PATH = os.path.join(SRC_PATH, 'themes')

#graphics
GRAPHICS_PATH = os.path.join(CONTRIB_PATH, 'graphics')
GRAPHICS_SRC_PATH = os.path.join(CONTRIB_PATH, GRAPHICS_PATH, 'src')

#closure tools
EXTERNS_PATH = os.path.join(PROJECT_PATH, 'externs.js')
COMPILER_PATH = os.path.join(CONTRIB_PATH, 'compiler', 'compiler.jar')
CLOSURE_LIBRARY_PATH = os.path.join(CONTRIB_PATH, 'closure-library')
CLOSURE_SOURCE_PATH = os.path.join(CLOSURE_LIBRARY_PATH, 'closure', 'goog')
CLOSURE_LINTER_WRAPPER_PATH = os.path.join(CONTRIB_PATH, 'closure-linter-wrapper')
CLOSURE_BIN_PATH = os.path.join(CLOSURE_LIBRARY_PATH, 'closure', 'bin')
DEPS_WRITER_PATH = os.path.join(CLOSURE_BIN_PATH, 'build', 'depswriter.py')
CLOSURE_BUILDER_PATH = os.path.join(CLOSURE_BIN_PATH, 'build', 'closurebuilder.py')


#=======================================================================================================================
#                            Utils
#=======================================================================================================================
def __create_dir_if_not_exists(path):
    if not os.path.exists(path):
        os.mkdir(path)


#=======================================================================================================================
#                            Synchronize contributions.
#=======================================================================================================================
def __has_closure_compiler():
    return os.path.exists(COMPILER_PATH)


def __need_sync_contrib():
    return not os.path.exists(COMPILER_PATH) or \
           not os.path.exists(CLOSURE_LIBRARY_PATH) or \
           not os.path.exists(GRAPHICS_PATH)


def __sync_contrib():
    __create_dir_if_not_exists(CONTRIB_PATH)

    subprocess.call(['git', 'submodule', 'init'])
    subprocess.call(['git', 'submodule', 'update'])
    subprocess.call(['rm', '-f', '.git/hooks/post-checkout'])
    subprocess.call(['ln', '-s', '../../update-submodules', '.git/hooks/post-checkout'])

    #Download closure compiler
    if not os.path.exists(COMPILER_PATH):
        print 'Download closure compiler'
        __download_and_unzip_from_http(
            'http://dl.google.com/closure-compiler/compiler-20151015.zip',
            'compiler'
        )

    #Install closure linter
    global arguments
    if 'linter' in arguments and arguments['linter']:
        __install_closure_linter()

    print 'All contributions installed'


def __download_and_unzip_from_http(from_url, dri_name):
    z_obj_path = os.path.join(CONTRIB_PATH, dri_name + '.zip')

    # download zip archive from url
    if not os.path.exists(z_obj_path):
        urllib.urlretrieve(
            from_url,
            z_obj_path
        )

    # extract zip archive
    target_path = os.path.join(CONTRIB_PATH, dri_name)
    __create_dir_if_not_exists(target_path)
    z_obj = zipfile.ZipFile(z_obj_path)
    z_obj.extractall(path=target_path)
    z_obj.close()

    # remove archive file
    os.remove(z_obj_path)
    print 'Download successful'


def __install_closure_linter():
    print 'Install closure linter'
    commands = [] if platform.system() == 'Windows' else ['sudo']
    commands.append('easy_install')
    commands.append('https://closure-linter.googlecode.com/files/closure_linter-2.3.9.tar.gz')
    try:
        subprocess.call(commands)
    except StandardError:
        raise StandardError('Sync contribution failed: you should install easy_install module for python')


def sync_required(func):
    def wrapper():
        if __need_sync_contrib():
            __sync_contrib()
        func()

    return wrapper


#=======================================================================================================================
#                            Compiler flags generation.
#=======================================================================================================================
class OptimizationLevel:
    NONE = 0
    SIMPLE = 1
    ADVANCED = 2


def __add_option(flags, flag_name, flag_value):
    flags.append('--' + flag_name + ' ' + flag_value)


def __set_pretty_print(flags):
    __add_option(flags, 'formatting', 'PRETTY_PRINT')


def __set_optimization_level(flags, level):
    #set compiler level
    if level == OptimizationLevel.NONE:
        __add_option(flags, 'compilation_level', 'WHITESPACE_ONLY')
    elif level == OptimizationLevel.SIMPLE:
        __add_option(flags, 'compilation_level', 'SIMPLE_OPTIMIZATIONS')
    elif level == OptimizationLevel.ADVANCED:
        __add_option(flags, 'compilation_level', 'ADVANCED_OPTIMIZATIONS')


def __get_output_file_arg(output_file):
    return ['--js_output_file ' + output_file]


def __get_name_spaces(modules):
    result = []
    for module in modules:
        result.append("--closure_entry_point anychart.modules.%s" % module)
    return result


def __get_roots():
    return ['--js="%s"' % os.path.join(SRC_PATH, '**.js'),
            '--js="%s"' % os.path.join(CLOSURE_LIBRARY_PATH, '**.js'),
            '--js="%s"' % os.path.join(GRAPHICS_SRC_PATH, '**.js')]


def __get_not_optimized_compiler_args():
    compiler_args = []
    __set_optimization_level(compiler_args, OptimizationLevel.NONE)
    __set_pretty_print(compiler_args)
    return compiler_args


def __get_developers_edition_compiler_args():
    flag = 'true' if __is_develop() else 'false'
    return [
        '--define "goog.DEBUG=%s"' % flag,
        '--define "anychart.DEVELOP=%s"' % flag,
    ]


def __get_toolbar_css_compiler_args(modules):
    if ('anychart' in modules) or ('toolbar' in modules) or ('anygantt' in modules) or ('anychart_bundle' in modules):
        with open(CSS_PATH, 'r') as css_file:
            #Removing new lines
            css_data = css_file.read().replace('\n', '')

            #Removing comments
            css_data = re.sub('\/\*[^*]*\*+([^/*][^*]*\*+)*\/', '', css_data)

            #Removing multiple spaces
            css_data = re.sub('\s\s+', ' ', css_data)

        return [
            '--define "anychart.TOOLBAR_CSS=\'%s\'"' % css_data
        ]

    return []


def __get_optimized_compiler_args():
    compiler_args = [
        '--warning_level VERBOSE',
        '--jscomp_warning accessControls',
        '--jscomp_warning ambiguousFunctionDecl',
        '--jscomp_warning checkDebuggerStatement',
        '--jscomp_warning checkEventfulObjectDisposal',
        '--jscomp_warning checkRegExp',
        '--jscomp_warning checkTypes',
        '--jscomp_warning checkVars',
        '--jscomp_warning closureDepMethodUsageChecks',
        '--jscomp_warning conformanceViolations',
        '--jscomp_warning const',
        '--jscomp_warning constantProperty',
        '--jscomp_warning deprecated',
        '--jscomp_warning deprecatedAnnotations',
        '--jscomp_warning duplicate',
        '--jscomp_warning duplicateMessage',
        '--jscomp_warning es3',
        '--jscomp_warning es5Strict',
        '--jscomp_warning externsValidation',
        '--jscomp_warning extraRequire',
        '--jscomp_warning fileoverviewTags',
        '--jscomp_warning globalThis',
        '--jscomp_warning inferredConstCheck',
        '--jscomp_warning internetExplorerChecks',
        '--jscomp_warning invalidCasts',
        '--jscomp_warning misplacedTypeAnnotation',
        '--jscomp_warning missingGetCssName',
        '--jscomp_warning missingProperties',
        '--jscomp_warning missingProvide',
        '--jscomp_warning missingRequire',
        '--jscomp_warning missingReturn',
        '--jscomp_warning newCheckTypes',
        #'--jscomp_warning msgDescriptionsNewCheckTypes',
        '--jscomp_warning nonStandardJsDocs',
        #'--jscomp_warning reportUnknownTypes',
        '--jscomp_warning suspiciousCode',
        '--jscomp_warning strictModuleDepCheck',
        '--jscomp_warning tweakValidation',
        '--jscomp_warning typeInvalidation',
        '--jscomp_warning undefinedNames',
        '--jscomp_warning undefinedVars',
        '--jscomp_warning unknownDefines',
        #+'--jscomp_warning unnecessaryCasts',
        '--jscomp_warning uselessCode',
        #+'--jscomp_warning useOfGoogBase',
        '--jscomp_warning violatedModuleDep',
        '--jscomp_warning visibility',
    ]
    __set_optimization_level(compiler_args, OptimizationLevel.ADVANCED)
    return compiler_args


def __get_default_compiler_args():
    global arguments
    result = [
        'java -jar',
        COMPILER_PATH,
        '--charset UTF-8',
        '--define "anychart.VERSION=\'%s\'"' % __get_version(True),
        '--only_closure_dependencies',
        #'--process_closure_primitives',
        #'--use_types_for_optimization',
        #'--use_only_custom_externs',
        '--externs ' + EXTERNS_PATH,
        '--extra_annotation_name "includeDoc"',
        '--extra_annotation_name "illustration"',
        '--extra_annotation_name "illustrationDesc"',
        '--extra_annotation_name "ignoreDoc"',
        '--extra_annotation_name "propertyDoc"',
        '--extra_annotation_name "shortDescription"',
    ]

    theme = arguments['theme'] if ('theme' in arguments) else 'defaultTheme'
    if not (theme == 'none'):
        if not os.path.exists(os.path.join(SRC_PATH, 'themes', theme + '.js')):
            theme = 'defaultTheme'
        result = result + ['--define "anychart.DEFAULT_THEME=\'%s\'"' % theme]
        result = result + ['--closure_entry_point "%s"' % 'anychart.themes.' + theme]
    return result


#=======================================================================================================================
#           Build project
#=======================================================================================================================
@sync_required
def __compile_project_each():
    global arguments
    arguments['sources'] = False
    modules = __get_modules_list()
    for module in modules:
        arguments['modules'] = [str(module)]
        __compile_project()


@sync_required
def __compile_project():
    t = time.time()
    global arguments

    modules = arguments['modules'] if arguments['modules'] else ['anychart_bundle']
    if not __is_allowed_modules(modules):
        raise Exception("Wrong modules: %s" % ', '.join(modules))

    __create_dir_if_not_exists(OUT_PATH)

    if arguments['sources']:
        __build_project_sources(modules)
    __build_project(modules)

    print "[PY] compile time: {:.3f} sec".format(time.time() - t)


def __build_project_sources(modules):
    dev_postfix = '.dev' if __is_develop() else ''
    file_name = "%s%s%s" % ('_'.join(modules), dev_postfix, '.js')
    file_name = __apply_specific_file_name_rule(file_name, modules)
    output_file = os.path.join(OUT_PATH, file_name)
    print "Compile source file for modules: %s\nOutput: %s\nVersion: %s\nDevelopers edition: %s" % (
        ', '.join(modules), output_file, __get_version(True), str(arguments['develop']))
    commands = __get_default_compiler_args() + \
               __get_not_optimized_compiler_args() + \
               __get_developers_edition_compiler_args() + \
               __get_toolbar_css_compiler_args(modules) + \
               __get_name_spaces(modules) + \
               __get_roots() + \
               __get_output_file_arg(output_file)
    __call_console_commands(commands)

    if 'gzip' in arguments:
        __gzip(output_file)


def __get_copyrigth(modules):
    if len(modules) != 1 or modules[0] not in ['anychart_bundle', 'anychart', 'anymap', 'anygantt', 'anystock']:
        return ''

    module = modules[0]

    robust = 'Robust ' if module in ['anychart', 'anychart_bundle'] else ''

    title = ''
    name = ''
    if module == 'anychart_bundle':
        name = 'AnyChart'
        title = 'Charting Framework\n * AnyChart, AnyMap, AnyGantt, AnyStock'
    elif module == 'anychart':
        name = 'AnyChart'
        title = 'Charts'
    elif module == 'anymap':
        name = 'AnyMap'
        title = 'Maps'
    elif module == 'anygantt':
        name = 'AnyGantt'
        title = 'Gantt Charts'
    elif module == 'anystock':
        name = 'AnyStock'
        title = 'Financial Charts'

    build = 'Development' if __is_develop() else 'Production'

    version = __get_version(False)

    url = ''
    if not module == 'anychart_bundle':
        url = '/products/%s/' % module

    copyright =\
        "/* %s - %sJavaScript HTML5 Web %s\n"\
        " * %s Build\n"\
        " * Version: %s\n"\
        " * http://anychart.com%s\n"\
        " */\n" % (name, robust, title, build, version, url)
    return copyright


def __build_project(modules):
    dev_postfix = '.dev' if __is_develop() else ''
    file_name = "%s%s%s" % ('_'.join(modules), dev_postfix, '.min.js')
    file_name = __apply_specific_file_name_rule(file_name, modules)
    output_file = os.path.join(OUT_PATH, file_name)
    print output_file
    print "Compile binary file for modules: %s\nOutput: %s\nVersion: %s\nDevelopers edition: %s\nDebug files: %s\nGzip: %s \nTheme: %s" % (
        ', '.join(modules), output_file, __get_version(True), str(arguments['develop']), str(arguments['debug_files']),
        str(arguments['gzip']), str(arguments['theme']))
    copyright = __get_copyrigth(modules)
    commands = __get_default_compiler_args() + \
               __get_optimized_compiler_args() + \
               __get_developers_edition_compiler_args() + \
               __get_toolbar_css_compiler_args(modules) + \
               __get_name_spaces(modules) + \
               __get_roots() + \
               __get_output_file_arg(output_file) + \
               ['--output_wrapper "' + copyright + '(function(){%output%})()' + '%s"' % (('//# sourceMappingURL=%s.map' % file_name) if __should_gen_debug_files() else '')]

    #debug info
    if __should_gen_debug_files():
        path = PROJECT_PATH.replace('\\', '/')
        print path
        commands += ['--property_renaming_report %s' % output_file + '_prop_out.txt',
                     '--variable_renaming_report %s' % output_file + '_var_out.txt',
                     '--create_source_map %s' % output_file + '.map',
                     '--source_map_location_mapping \"%s|http://localhost:63341/ACDVF\"' % path]

    __call_console_commands(commands)

    if __should_gen_gzip():
        __gzip(output_file)


def __apply_specific_file_name_rule(file_name, modules):
    if modules == ['anychart_bundle']:
        file_name = file_name.replace('anychart_bundle', 'anychart-bundle')
    return file_name


def __call_console_commands(commands):
    commands = " ".join(commands).replace('\\', '\\\\')
    commands = shlex.split(commands)
    #print commands
    p = subprocess.Popen(commands, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    (output, err) = p.communicate()
    retcode = p.poll()
    print output


def __is_allowed_modules(modules):
    l = __get_modules_list()
    for module in modules:
        if not module in l:
            return False
    return True


modules_list_cache = None


def __get_modules_list():
    global modules_list_cache
    if modules_list_cache is None:

        modules_list_cache = []
        for f in os.listdir(MODULES_PATH):
            if f.endswith('.js'):
                modules_list_cache.append(f[:-3])
    return modules_list_cache


def __gzip(output_file):
    f_in = open(output_file, 'rb')
    f_out = gzip.open(output_file + '.gz', 'wb')
    f_out.writelines(f_in)
    f_out.close()
    f_in.close()


#=======================================================================================================================
#           Build deps
#=======================================================================================================================
@sync_required
def __build_deps():
    output_file = os.path.join(SRC_PATH, 'deps.js')
    print "Writing deps to %s" % output_file
    subprocess.call([
        'python',
        DEPS_WRITER_PATH,
        '--root_with_prefix=%s %s' % (SRC_PATH, os.path.relpath(SRC_PATH, CLOSURE_SOURCE_PATH)),
        '--root_with_prefix=%s %s' % (GRAPHICS_SRC_PATH, os.path.relpath(GRAPHICS_SRC_PATH, CLOSURE_SOURCE_PATH)),
        '--output_file=' + output_file
    ])


#=======================================================================================================================
#                            Linter.
#=======================================================================================================================
@sync_required
def __lint_project():
    print 'Search for lint errors\n'
    subprocess.call([
        'python',
        os.path.join(CLOSURE_LINTER_WRAPPER_PATH, 'gjslint.py'),
        '--flagfile',
        'gjslint.cfg',
        '-r',
        SRC_PATH,
        '-r',
        GRAPHICS_SRC_PATH
    ])

    print 'Search for JSDoc continuation \n'
    source = []
    for dir_name, dir_names, file_names in os.walk(SRC_PATH):
        for filename in file_names:
            source.append(os.path.join(dir_name, filename))
    file_with_errors = ''
    for filename in source:
        path = os.path.join(PROJECT_PATH, filename)
        data = open(path).read()
        if re.search('\*\/\n\/\*\*', data):
            file_with_errors += path + ' '
    print file_with_errors.replace(' ', '\n') + 'RUN AUTOFIX to fix this\n' if (len(file_with_errors) > 0) else 'ok'


#=======================================================================================================================
#                            Linter Autofix.
#=======================================================================================================================
@sync_required
def __autofix_project():
    print 'Trying to autofix lint errors\n'
    subprocess.call([
        'python',
        os.path.join(CLOSURE_LINTER_WRAPPER_PATH, 'fixjsstyle.py'),
        '--flagfile',
        'gjslint.cfg',
        '-r',
        SRC_PATH
    ])

    print 'Trying to autofix JSDoc continuation errors\n'
    source = []
    for dir_name, dir_names, file_names in os.walk(SRC_PATH):
        for filename in file_names:
            source.append(os.path.join(dir_name, filename))
    files_with_errors = ''
    for filename in source:
        path = os.path.join(PROJECT_PATH, filename)
        data = open(path).read()
        if re.search('\*\/\n\/\*\*', data):
            files_with_errors += path + ' '
            o = open(path, 'w')
            o.write(re.sub('\*\/\n\/\*\*', '*//**', data))
            o.close()
            print 'fixed ' + path


#=======================================================================================================================
#                            Themes.
#=======================================================================================================================
def __get_themes_list():
    themes_list = []
    for f in os.listdir(THEMES_PATH):
        if f.endswith('.js') and not f.startswith('merging') and not f.startswith('template'):
            themes_list.append(f[:-3])
    return themes_list


@sync_required
def __build_theme():
    global arguments
    theme = arguments['name']

    if theme in __get_themes_list():
        print "Compile standalone theme %s" % theme
        commands = [
            'java -jar',
            COMPILER_PATH,
            '--charset UTF-8',
            '--only_closure_dependencies',
            '--warning_level VERBOSE',
            '--compilation_level ADVANCED_OPTIMIZATIONS',
            "--closure_entry_point anychart.themes.%s" % theme,
            "--js_output_file %s" % os.path.join(OUT_PATH, theme + '.min.js')
        ] + __get_roots()
        __call_console_commands(commands)
        print "Complete"
    else:
        print "Wrong theme name %s" % theme

#=======================================================================================================================
#                            Build release.
#=======================================================================================================================
@sync_required
def __build_release():

    #bubdle
    print "Compile AnyChart Bundle"
    __call_console_commands(['./build compile -gz'])
    __call_console_commands(['./build compile -gz -d'])

    #charts
    print "Compile AnyChart"
    __call_console_commands(['./build compile -m anychart -gz'])
    __call_console_commands(['./build compile -m anychart -gz -d'])

    #map
    print "Compile AnyMap"
    __call_console_commands(['./build compile -m anymap -gz'])
    __call_console_commands(['./build compile -m anymap -gz -d'])

    #stock
    print "Compile AnyStock"
    __call_console_commands(['./build compile -m anystock -gz'])
    __call_console_commands(['./build compile -m anystock -gz -d'])

    #gantt
    print "Compile AnyGantt"
    __call_console_commands(['./build compile -m anygantt -gz'])
    __call_console_commands(['./build compile -m anygantt -gz -d'])

    print "Compile Themes"
    for theme in __get_themes_list():
        __call_console_commands(['./build theme -n %s' % theme])


def __print_gz_stat():
    result = []

    for f in os.listdir(OUT_PATH):
        if f.endswith('.gz'):
            full_path = os.path.join(OUT_PATH, f)
            stat = os.stat(full_path)
            result.append("%s size is %s" % (f, str(stat.st_size/1024) + "Kb"))

    if len(result):
        print "Looking for gzip files size in out directory:"
        print "    " + "\n    ".join(result)
    else:
        print "No gzip files found in out directory"


#=======================================================================================================================
#                            Logging.
#=======================================================================================================================
warnings_list = []


def __print_no_bundles():
    print 'No bundles found, see help for more info. (python build --help)'


def __print_warnings_list():
    for msg in warnings_list:
        print '\nWarning:'
        print msg


#=======================================================================================================================
#                            Version.
#=======================================================================================================================
def __get_version(opt_commits_count=False):
    #get global, major, minor versions from version.ini
    version_file = os.path.join(PROJECT_PATH, 'version.ini')
    f = open(version_file, 'r')
    lines = f.readlines()
    f.close()

    major = lines[0].split('=')[1].strip()
    minor = lines[1].split('=')[1].strip()
    patch = lines[2].split('=')[1].strip()

    if opt_commits_count:
        #get commits count from git repo
        p = subprocess.Popen(
            ['git', 'rev-list', 'HEAD', '--count'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=PROJECT_PATH)
        (output, err) = p.communicate()
        commit_count = output.strip()

        return "%s.%s.%s.%s" % (major, minor, patch, commit_count)
    else:
        return "%s.%s.%s" % (major, minor, patch)


def __is_develop():
    global arguments
    return 'develop' in arguments and str(arguments['develop']) == 'True'


def __should_gen_debug_files():
    global arguments
    return 'debug_files' in arguments and str(arguments['debug_files']) == 'True'


def __should_gen_gzip():
    global arguments
    return 'gzip' in arguments and str(arguments['gzip']) == 'True'


#=======================================================================================================================
#           Main
#=======================================================================================================================
arguments = {}


def __exec_main_script():
    #root parser
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help='AnyChart framework build script commands:')

    # create the parser for the "compile" command
    compile_parser = subparsers.add_parser('compile', help='Compile project or project modules')
    compile_parser.add_argument('-m', '--module', dest='modules', action='append',
                                help="Specify modules to compile, can be specified multiple times. Possible modules values: %s" % ', '.join(
                                    __get_modules_list()))
    compile_parser.add_argument('-s', '--sources', action='store_true',
                                help='Build project sources file (not minimized).')
    compile_parser.add_argument('-d', '--develop', action='store_true', help='Include developers tools into build.')
    compile_parser.add_argument('-gz', '--gzip', action='store_true', help='Create gzip copy of output file.')
    compile_parser.add_argument('-df', '--debug_files', action='store_true',
                                help='Create files with debug info (prop_out, var_out, sourcemap).')
    compile_parser.add_argument('-t', '--theme', action='store',
                                help="Specify the default theme to compile with. By default - 'defaultTheme'",
                                default='defaultTheme')

    # create the parser for the "compile_each" command
    compile_each_parser = subparsers.add_parser('compile_each', help='Compile each project available module')
    compile_each_parser.add_argument('-d', '--develop', action='store_true',
                                     help='Include developers tools flag in each module compilation.')
    compile_each_parser.add_argument('-df', '--debug_files', action='store_true',
                                     help='Create files with debug info (prop_out, var_out, sourcemap).')
    compile_each_parser.add_argument('-gz', '--gzip', action='store_true', help='Create gzip copy of output file.')
    compile_each_parser.add_argument('-t', '--theme', action='store',
                                     help="Specify the default theme to compile with. By default - 'defaultTheme'",
                                     default='defaultTheme')

    # create the parser for the "contrib" command
    contrib_parser = subparsers.add_parser('contrib', help='Synchronize project dependencies')
    contrib_parser.add_argument('-l', '--linter', action='store_true',
                                help='Install closure linter with others contributions.')

    # create the parser for the "deps" command
    subparsers.add_parser('deps', help='Generate deps.js file')

    # create the parser for the "lint" command
    subparsers.add_parser('lint', help='Exec linter check for whole project')

    # create the parser for the "contrib" command
    subparsers.add_parser('autofix', help='Try to autofix linter warnings and errors')

    # create the parser for the "theme" command
    themes_parser = subparsers.add_parser('theme',
                                          help='Build standalone theme file by name. Default value is "defaultTheme"')
    themes_parser.add_argument('-n', '--name', action='store',
                               help="Name of the theme, default value is 'defaultTheme'.\nPossible values are: %s"
                                    % ", ".join(__get_themes_list()), default='defaultTheme')
    # create files for release
    subparsers.add_parser('release', help='Creates release files in output directory.')

    # create files for release
    subparsers.add_parser('gz_stat', help='Print into console size of all gzip files in out directory,'
                                          ' very useful on release day.')

    global arguments
    arguments = vars(parser.parse_args())

    command = sys.argv[1]

    if command == 'contrib':
        __sync_contrib()
    elif command == 'compile':
        __compile_project()
    elif command == 'compile_each':
        __compile_project_each()
    elif command == 'deps':
        __build_deps()
    elif command == 'lint':
        __lint_project()
    elif command == 'autofix':
        __autofix_project()
    elif command == 'theme':
        __build_theme()
    elif command == 'release':
        __build_release()
    elif command == 'gz_stat':
        __print_gz_stat()

    __print_warnings_list()


if __name__ == '__main__':
    try:
        __exec_main_script()
    except StandardError as e:
        print e
        sys.exit(1)