/**
 * @license Highcharts 4.1.9 JS v/Highstock 2.1.9 (2015-10-07)
 *
 * Standalone Highcharts Framework
 *
 * License: MIT License
 */

window.highcharts_init_start=(typeof window.performance=='object')&&(typeof window.performance.now=='function')?window.performance.now():+new Date();

/*
 Highcharts 4.1.9 JS v/Highstock 2.1.9 (2015-10-07)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
 */
(function(){function D(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function E(a,b){return parseInt(a,b||10)}function ca(a){return"string"===typeof a}function da(a){return a&&
		"object"===typeof a}function pa(a){return"[object Array]"===Object.prototype.toString.call(a)}function ga(a){return"number"===typeof a}function Ja(a){return N.log(a)/N.LN10}function ea(a){return N.pow(10,a)}function qa(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function v(a){return a!==y&&null!==a}function I(a,b,c){var d,e;if(ca(b))v(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(v(b)&&da(b))for(d in b)a.setAttribute(d,b[d]);return e}function ra(a){return pa(a)?
		a:[a]}function R(a,b){Y&&!S&&b&&b.opacity!==y&&(b.filter="alpha(opacity="+100*b.opacity+")");B(a.style,b)}function sa(a,b,c,d,e){a=F.createElement(a);b&&B(a,b);e&&R(a,{padding:0,border:"none",margin:0});c&&R(a,c);d&&d.appendChild(a);return a}function Ua(a,b){var c=function(){return y};c.prototype=new a;B(c.prototype,b);return c}function ha(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function xa(a,b){for(var c="{",d=!1,e,f,g,h,k,m=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");
	g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=L.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=z.numberFormat(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=ya(f,e))}m.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}m.push(a);return m.join("")}function mb(a,b,c,d,e){var f,g=a;c=r(c,1);f=a/c;b||(b=[1,2,2.5,5,10],!1===d&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(g=b[d],e&&g*c>=a||!e&&f<=(b[d]+(b[d+
1]||b[d]))/2);d++);return g*c}function Ka(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function za(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function ta(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function Aa(a,b){for(var c in a)a[c]&&a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function Ba(a){Ca||(Ca=sa("div"));a&&Ca.appendChild(a);Ca.innerHTML=""}function T(a,
		b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;K.console&&console.log(c)}function Z(a,b){return parseFloat(a.toPrecision(b||14))}function Va(){var a=L.global,b=a.useUTC,c=b?"getUTC":"get",d=b?"setUTC":"set";La=a.Date||window.Date;Wa=b&&a.timezoneOffset;Ma=b&&a.getTimezoneOffset;Xa=c+"Minutes";Ya=c+"Hours";Za=c+"Day";$a=c+"Date";Na=c+"Month";Oa=c+"FullYear";ab=d+"Month";bb=d+"FullYear"}function M(){}function ma(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=
		!0;c||d||this.addLabel()}var y,F=document,K=window,N=Math,C=N.round,U=N.floor,aa=N.ceil,w=N.max,G=N.min,V=N.abs,ia=N.cos,na=N.sin,cb=N.PI,oa=2*cb/360,ja=navigator.userAgent,nb=K.opera,Y=/(msie|trident|edge)/i.test(ja)&&!nb,db=!Y&&/AppleWebKit/.test(ja),ua=/Firefox/.test(ja),eb=/(Mobile|Android|Windows Phone)/.test(ja),S=!!F.createElementNS&&!!F.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,ob=ua&&4>parseInt(ja.split("Firefox/")[1],10),ba=!S&&!Y&&!!F.createElement("canvas").getContext,
		fb={},Pa=0,Ca,L,ya,Qa,fa=[],gb=0,pb=/^[0-9]+$/,Da=["plotTop","marginRight","marginBottom","plotLeft"],La,Wa,Ma,Xa,Ya,Za,$a,Na,Oa,ab,bb,va={},z;z=K.Highcharts=K.Highcharts?T(16,!0):{};z.seriesTypes=va;var B=z.extend=function(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a},r=z.pick=function(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==y&&null!==c)return c},hb=z.wrap=function(a,b,c){var d=a[b];a[b]=function(){var a=Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,
		a)}};ya=function(a,b,c){if(!v(b)||isNaN(b))return L.lang.invalidDate||"";a=r(a,"%Y-%m-%d %H:%M:%S");var d=new La(b-6E4*(Ma&&Ma(b)||Wa||0)),e,f=d[Ya](),g=d[Za](),h=d[$a](),k=d[Na](),m=d[Oa](),l=L.lang,q=l.weekdays,d=B({a:q[g].substr(0,3),A:q[g],d:ha(h),e:h,w:g,b:l.shortMonths[k],B:l.months[k],m:ha(k+1),y:m.toString().substr(2,2),Y:m,H:ha(f),k:f,I:ha(f%12||12),l:f%12||12,M:ha(d[Xa]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",S:ha(d.getSeconds()),L:ha(C(b%1E3),3)},z.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+
		e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};z.numberFormat=function(a,b,c,d){var e=L.lang;a=+a||0;var f=-1===b?G((a.toString().split(".")[1]||"").length,20):isNaN(b=V(b))?2:b;b=void 0===c?e.decimalPoint:c;d=void 0===d?e.thousandsSep:d;e=0>a?"-":"";c=String(E(a=V(a).toFixed(f)));var g=3<c.length?c.length%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+V(a-c).toFixed(f).slice(2):"")};Qa={init:function(a,
		b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,m=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(m(b),m(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));
	return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};(function(a){K.HighchartsAdapter=K.HighchartsAdapter||a&&{init:function(b){var c=a.fx;a.extend(a.easing,{easeOutQuad:function(a,b,c,g,h){return-g*(b/=h)*(b-2)+c}});a.each(["cur","_default","width","height","opacity"],function(b,e){var f=c.step,g;"cur"===e?f=c.prototype:"_default"===e&&a.Tween&&(f=a.Tween.propHooks[e],
				e="set");(g=f[e])&&(f[e]=function(a){var c;a=b?a:this;if("align"!==a.prop)return c=a.elem,c.attr?c.attr(a.prop,"cur"===e?y:a.now):g.apply(this,arguments)})});hb(a.cssHooks.opacity,"get",function(a,b,c){return b.attr?b.opacity||0:a.call(this,b,c)});this.addAnimSetter("d",function(a){var c=a.elem,f;a.started||(f=b.init(c,c.d,c.toD),a.start=f[0],a.end=f[1],a.started=!0);c.attr("d",b.step(a.start,a.end,a.pos,c.toD))});this.each=Array.prototype.forEach?function(a,b){return Array.prototype.forEach.call(a,
				b)}:function(a,b){var c,g=a.length;for(c=0;c<g;c++)if(!1===b.call(a[c],a[c],c,a))return c};a.fn.highcharts=function(){var a="Chart",b=arguments,c,g;this[0]&&(ca(b[0])&&(a=b[0],b=Array.prototype.slice.call(b,1)),c=b[0],c!==y&&(c.chart=c.chart||{},c.chart.renderTo=this[0],new z[a](c,b[1]),g=this),c===y&&(g=fa[I(this[0],"data-highcharts-chart")]));return g}},addAnimSetter:function(b,c){a.Tween?a.Tween.propHooks[b]={set:c}:a.fx.step[b]=c},getScript:a.getScript,inArray:a.inArray,adapterRun:function(b,
				c){return a(b)[c]()},grep:a.grep,map:function(a,c){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=c.call(a[e],a[e],e,a);return d},offset:function(b){return a(b).offset()},addEvent:function(b,c,d){a(b).bind(c,d)},removeEvent:function(b,c,d){var e=F.removeEventListener?"removeEventListener":"detachEvent";F[e]&&b&&!b[e]&&(b[e]=function(){});a(b).unbind(c,d)},fireEvent:function(b,c,d,e){var f=a.Event(c),g="detached"+c,h;!Y&&d&&(delete d.layerX,delete d.layerY,delete d.returnValue);B(f,d);b[c]&&(b[g]=b[c],b[c]=
				null);a.each(["preventDefault","stopPropagation"],function(a,b){var c=f[b];f[b]=function(){try{c.call(f)}catch(a){"preventDefault"===b&&(h=!0)}}});a(b).trigger(f);b[g]&&(b[c]=b[g],b[g]=null);!e||f.isDefaultPrevented()||h||e(f)},washMouseEvent:function(a){var c=a.originalEvent||a;c.pageX===y&&(c.pageX=a.pageX,c.pageY=a.pageY);return c},animate:function(b,c,d){var e=a(b);b.style||(b.style={});c.d&&(b.toD=c.d,c.d=1);e.stop();c.opacity!==y&&b.attr&&(c.opacity+="px");b.hasAnim=1;e.animate(c,d)},stop:function(b){b.hasAnim&&
		a(b).stop()}}})(K.jQuery);var Ea=K.HighchartsAdapter,X=Ea||{};Ea&&Ea.init.call(Ea,Qa);var Fa=X.adapterRun,qb=X.inArray,t=z.each=X.each,Ra=X.grep,ib=X.map,P=X.addEvent,W=X.removeEvent,Q=X.fireEvent,jb=X.animate,kb=X.stop;L={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #2b908f #f45b5b #91e8e1".split(" "),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),
	shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.1.9/modules/canvas-tools.js",VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.1.9/gfx/vml-radial-gradient.png"},
	chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,
		radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:{align:"center",formatter:function(){return null===this.y?"":z.numberFormat(this.y,-1)},style:{color:"contrast",fontSize:"11px",fontWeight:"bold",textShadow:"0 0 6px contrast, 0 0 3px contrast"},verticalAlign:"bottom",x:0,y:0,padding:5},cropThreshold:300,pointRange:0,softThreshold:!0,states:{hover:{lineWidthPlus:1,marker:{},
		halo:{size:10,opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",
		width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:S,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",
		day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},footerFormat:"",headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:eb?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",pointerEvents:"none",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,
		verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Ga=L.plotOptions;Va();var rb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,sb=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,tb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,ka=function(a){var b=[],c,d;(function(a){a&&a.stops?d=ib(a.stops,function(a){return ka(a[1])}):(c=rb.exec(a))?b=[E(c[1]),E(c[2]),E(c[3]),parseFloat(c[4],10)]:(c=sb.exec(a))?
		b=[E(c[1],16),E(c[2],16),E(c[3],16),1]:(c=tb.exec(a))&&(b=[E(c[1]),E(c[2]),E(c[3]),1])})(a);return{get:function(c){var f;d?(f=D(a),f.stops=[].concat(f.stops),t(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)t(d,function(b){b.brighten(a)});else if(ga(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=E(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,
	setOpacity:function(a){b[3]=a;return this},raw:a}};M.prototype={opacity:1,textProps:"fontSize fontWeight fontFamily fontStyle color lineHeight width textDecoration textOverflow textShadow".split(" "),init:function(a,b){this.element="span"===b?sa(b):F.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=r(b,this.renderer.globalAnimation,!0);kb(this);b?(b=D(b,{}),c&&(b.complete=c),jb(this,a,b)):this.attr(a,null,c);return this},colorGradient:function(a,b,c){var d=
		this.renderer,e,f,g,h,k,m,l,q,p,n,x,u=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];k=d.gradients;l=a.stops;n=c.radialReference;pa(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&n&&!v(g.gradientUnits)&&(h=g,g=D(g,d.getRadialAttr(n,h),{gradientUnits:"userSpaceOnUse"}));for(x in g)"id"!==x&&u.push(x,g[x]);for(x in l)u.push(l[x]);u=u.join(",");k[u]?a=k[u].attr("id"):(g.id=a="highcharts-"+Pa++,k[u]=m=d.createElement(f).attr(g).add(d.defs),
		m.radAttr=h,m.stops=[],t(l,function(a){0===a[1].indexOf("rgba")?(e=ka(a[1]),q=e.get("rgb"),p=e.get("a")):(q=a[1],p=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":q,"stop-opacity":p}).add(m);m.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")");c.gradient=u}},applyTextShadow:function(a){var b=this.element,c,d=-1!==a.indexOf("contrast"),e={},f=this.renderer.forExport,g=f||b.style.textShadow!==y&&!Y;d&&(e.textShadow=a=a.replace(/contrast/g,this.renderer.getContrast(b.style.fill)));
	if(db||f)e.textRendering="geometricPrecision";g?this.css(e):(this.fakeTS=!0,this.ySetter=this.xSetter,c=[].slice.call(b.getElementsByTagName("tspan")),t(a.split(/\s?,\s?/g),function(a){var d=b.firstChild,e,f;a=a.split(" ");e=a[a.length-1];(f=a[a.length-2])&&t(c,function(a,c){var g;0===c&&(a.setAttribute("x",b.getAttribute("x")),c=b.getAttribute("y"),a.setAttribute("y",c||0),null===c&&b.setAttribute("y",0));g=a.cloneNode(1);I(g,{"class":"highcharts-text-shadow",fill:e,stroke:e,"stroke-opacity":1/w(E(f),
			3),"stroke-width":f,"stroke-linejoin":"round"});b.insertBefore(g,d)})}))},attr:function(a,b,c){var d,e=this.element,f,g=this,h;"string"===typeof a&&b!==y&&(d=a,a={},a[d]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(d in a)b=a[d],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(d)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==d&&"y"!==d||(this.doTransform=!0),h||(this[d+"Setter"]||this._defaultSetter).call(this,
		b,d,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(d)&&this.updateShadows(d,b);this.doTransform&&(this.updateTransform(),this.doTransform=!1)}c&&c();return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?w(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=I(b,"class")||"";-1===c.indexOf(a)&&I(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;t("x y r start end width height innerR anchorX anchorY".split(" "),
		function(c){b[c]=r(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=C(e)%2/2;a.x=U(a.x||this.x||0)+d;a.y=U(a.y||this.y||0)+d;a.width=U((a.width||this.width||0)-2*d);a.height=U((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=
		this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&a.width&&"text"===d.nodeName.toLowerCase()&&E(a.width)||this.textWidth;b&&(a=B(b,c));this.styles=a;e&&(ba||!S&&this.renderer.forExport)&&delete a.width;if(Y&&!S)R(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";I(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,
		b){this.element["on"+a]=b;return this},setRadialReference:function(a){var b=this.renderer.gradients[this.element.gradient];this.element.radialReference=a;b&&b.radAttr&&b.animate(this.renderer.getRadialAttr(a,b.radAttr));return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,
		g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");(v(c)||v(d))&&a.push("scale("+r(c,1)+" "+r(d,1)+")");a.length&&g.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=
				b,!c||ca(c))this.alignTo=d=c||"renderer",qa(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=r(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];h[b?"translateX":"x"]=C(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=C(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=
		h;return this},getBBox:function(a){var b,c=this.renderer,d,e=this.rotation,f=this.element,g=this.styles,h=e*oa;d=this.textStr;var k,m=f.style,l,q;d!==y&&(q=["",e||0,g&&g.fontSize,f.style.width].join(),q=""===d||pb.test(d)?"num:"+d.toString().length+q:d+q);q&&!a&&(b=c.cache[q]);if(!b){if("http://www.w3.org/2000/svg"===f.namespaceURI||c.forExport){try{l=this.fakeTS&&function(a){t(f.querySelectorAll(".highcharts-text-shadow"),function(b){b.style.display=a})},ua&&m.textShadow?(k=m.textShadow,m.textShadow=
		""):l&&l("none"),b=f.getBBox?B({},f.getBBox()):{width:f.offsetWidth,height:f.offsetHeight},k?m.textShadow=k:l&&l("")}catch(p){}if(!b||0>b.width)b={width:0,height:0}}else b=this.htmlGetBBox();c.isSVG&&(a=b.width,d=b.height,Y&&g&&"11px"===g.fontSize&&"16.9"===d.toPrecision(3)&&(b.height=d=14),e&&(b.width=V(d*na(h))+V(a*ia(h)),b.height=V(d*ia(h))+V(a*na(h))));q&&(c.cache[q]=b)}return b},show:function(a){return this.attr({visibility:a?"inherit":"visible"})},hide:function(){return this.attr({visibility:"hidden"})},
	fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,c=this.element,d;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);this.added=!0;if(!a||a.handleZ||this.zIndex)d=this.zIndexSetter();d||(a?a.element:b.box).appendChild(c);if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=
			this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;kb(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&t(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&qa(a.renderer.alignedObjects,a);
		for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,m,l;if(a){k=r(a.width,3);m=(a.opacity||.15)/k;l=this.parentInverted?"(-1,-1)":"("+r(a.offsetX,1)+", "+r(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,I(f,{isShadow:"true",stroke:a.color||"black","stroke-opacity":m*e,"stroke-width":h,transform:"translate"+l,fill:"none"}),c&&(I(f,"height",w(I(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);
		this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=r(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot",
			"3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(b=a.length;b--;)a[b]=E(a[b])*this["stroke-width"];a=a.join(",").replace("NaN","none");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=
			this.element.getElementsByTagName("title")[0];b||(b=F.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.appendChild(F.createTextNode(String(r(a),"").replace(/<[^>]*>/g,"")))},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},visibilitySetter:function(a,b,c){"inherit"===a?c.removeAttribute(b):c.setAttribute(b,
			a)},zIndexSetter:function(a,b){var c=this.renderer,d=this.parentGroup,c=(d||c).element||c.box,e,f,g=this.element,h;e=this.added;var k;v(a)&&(g.setAttribute(b,a),a=+a,this[b]===a&&(e=!1),this[b]=a);if(e){(a=this.zIndex)&&d&&(d.handleZ=!0);d=c.childNodes;for(k=0;k<d.length&&!h;k++)e=d[k],f=I(e,"zIndex"),e!==g&&(E(f)>a||!v(a)&&v(f))&&(c.insertBefore(g,e),h=!0);h||c.appendChild(g)}return h},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};M.prototype.yGetter=M.prototype.xGetter;M.prototype.translateXSetter=
		M.prototype.translateYSetter=M.prototype.rotationSetter=M.prototype.verticalAlignSetter=M.prototype.scaleXSetter=M.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=!0};M.prototype["stroke-widthSetter"]=M.prototype.strokeSetter=function(a,b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],M.prototype.fillSetter.call(this,this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&
(c.removeAttribute("stroke"),this.hasStroke=!1)};var Ha=function(){this.init.apply(this,arguments)};Ha.prototype={Element:M,init:function(a,b,c,d,e,f){var g=location,h;d=this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));h=d.element;a.appendChild(h);-1===a.innerHTML.indexOf("xmlns")&&I(h,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=h;this.boxWrapper=d;this.alignedObjects=[];this.url=(ua||db)&&F.getElementsByTagName("base").length?g.href.replace(/#.*?$/,"").replace(/([\('\)])/g,
		"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(F.createTextNode("Created with Highcharts 4.1.9 /Highstock 2.1.9"));this.defs=this.createElement("defs").add();this.allowHTML=f;this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var k;ua&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){R(a,{left:0,top:0});k=a.getBoundingClientRect();R(a,{left:aa(k.left)-k.left+"px",top:aa(k.top)-k.top+"px"})},b(),P(K,"resize",b))},getStyle:function(a){return this.style=
		B({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();Aa(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&W(K,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},
	getRadialAttr:function(a,b){return{cx:a[0]-a[2]/2+b.cx*a[2],cy:a[1]-a[2]/2+b.cy*a[2],r:b.r*a[2]}},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=r(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,m=I(b,"x"),l=a.styles,q=a.textWidth,p=l&&l.lineHeight,n=l&&l.textShadow,x=l&&"ellipsis"===l.textOverflow,u=g.length,J=q&&!a.added&&this.box,A=function(a){return p?E(p):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:l&&l.fontSize||c.style.fontSize||12,
			a).h},v=function(a){return a.replace(/&lt;/g,"<").replace(/&gt;/g,">")};u--;)b.removeChild(g[u]);f||n||x||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,J&&J.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),t(e,function(e,f){var g,n=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,
			"</span>|||");g=e.split("|||");t(g,function(e){if(""!==e||1===g.length){var p={},u=F.createElementNS("http://www.w3.org/2000/svg","tspan"),r;h.test(e)&&(r=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),I(u,"style",r));k.test(e)&&!d&&(I(u,"onclick",'location.href="'+e.match(k)[1]+'"'),R(u,{cursor:"pointer"}));e=v(e.replace(/<(.|\n)*?>/g,"")||" ");if(" "!==e){u.appendChild(F.createTextNode(e));n?p.dx=0:f&&null!==m&&(p.x=m);I(u,p);b.appendChild(u);!n&&f&&(!S&&d&&R(u,{display:"block"}),I(u,"dy",
			A(u)));if(q){for(var p=e.replace(/([^\^])-/g,"$1- ").split(" "),t=1<g.length||f||1<p.length&&"nowrap"!==l.whiteSpace,J,wa,y,w=[],ub=A(u),C=1,B=a.rotation,z=e,D=z.length;(t||x)&&(p.length||w.length);)a.rotation=0,J=a.getBBox(!0),y=J.width,!S&&c.forExport&&(y=c.measureSpanWidth(u.firstChild.data,a.styles)),J=y>q,void 0===wa&&(wa=J),x&&wa?(D/=2,""===z||!J&&.5>D?p=[]:(J&&(wa=!0),z=e.substring(0,z.length+(J?-1:1)*aa(D)),p=[z+(3<q?"\u2026":"")],u.removeChild(u.firstChild))):J&&1!==p.length?(u.removeChild(u.firstChild),
			w.unshift(p.pop())):(p=w,w=[],p.length&&(C++,u=F.createElementNS("http://www.w3.org/2000/svg","tspan"),I(u,{dy:ub,x:m}),r&&I(u,"style",r),b.appendChild(u)),y>q&&(q=y)),p.length&&u.appendChild(F.createTextNode(p.join(" ").replace(/- /g,"-")));wa&&a.attr("title",a.textStr);a.rotation=B}n++}}})}),J&&J.removeChild(b),n&&a.applyTextShadow&&a.applyTextShadow(n)):b.appendChild(F.createTextNode(v(e)))},getContrast:function(a){a=ka(a).rgba;return 384<a[0]+a[1]+a[2]?"#000000":"#FFFFFF"},button:function(a,b,
			c,d,e,f,g,h,k){var m=this.label(a,b,c,k,null,null,null,null,"button"),l=0,q,p,n,x,u,r;a={x1:0,y1:0,x2:0,y2:1};e=D({"stroke-width":1,stroke:"#CCCCCC",fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);n=e.style;delete e.style;f=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);x=f.style;delete f.style;g=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);u=g.style;delete g.style;h=D(e,{style:{color:"#CCC"}},
			h);r=h.style;delete h.style;P(m.element,Y?"mouseover":"mouseenter",function(){3!==l&&m.attr(f).css(x)});P(m.element,Y?"mouseout":"mouseleave",function(){3!==l&&(q=[e,f,g][l],p=[n,x,u][l],m.attr(q).css(p))});m.setState=function(a){(m.state=l=a)?2===a?m.attr(g).css(u):3===a&&m.attr(h).css(r):m.attr(e).css(n)};return m.on("click",function(a){3!==l&&d.call(m,a)}).attr(e).css(B({cursor:"default"},n))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=C(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=C(a[2])+b%2/2);
		return a},path:function(a){var b={fill:"none"};pa(a)?b.d=a:da(a)&&B(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=da(a)?a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){da(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,
			b,c,d,e,f){e=da(a)?a.r:e;var g=this.createElement("rect");a=da(a)?a:a===y?{}:{x:a,y:b,width:w(c,0),height:w(d,0)};f!==y&&(a.strokeWidth=f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){I(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[r(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return v(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,
			b,c,d,e){var f={preserveAspectRatio:"none"};1<arguments.length&&B(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(C(b),C(c),d,e,f),k=/^url\((.*?)\)$/,m,l;h?(g=this.path(h),B(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&B(g,f)):k.test(a)&&(l=function(a,b){a.element&&(a.attr({width:b[0],
		height:b[1]}),a.alignByTranslate||a.translate(C((d-b[0])/2),C((e-b[1])/2)))},m=a.match(k)[1],a=fb[m]||f&&f.width&&f.height&&[f.width,f.height],g=this.image(m).attr({x:b,y:c}),g.isImg=!0,a?l(g,a):(g.attr({width:0,height:0}),sa("img",{onload:function(){0===this.width&&(R(this,{position:"absolute",top:"-999em"}),document.body.appendChild(this));l(g,fb[m]=[this.width,this.height]);this.parentNode&&this.parentNode.removeChild(this)},src:m})));return g},symbols:{circle:function(a,b,c,d){var e=.166*c;return["M",
		a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;d=e.innerR;var h=e.open,k=ia(f),m=na(f),l=ia(g),g=na(g);e=e.end-
	f<cb?0:1;return["M",a+c*k,b+c*m,"A",c,c,0,e,1,a+c*l,b+c*g,h?"M":"L",a+d*l,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*m,h?"":"Z"]},callout:function(a,b,c,d,e){var f=G(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX;e=e&&e.anchorY;var k;k=["M",a+f,b,"L",a+c-f,b,"C",a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&e>b+g&&e<b+d-g?k.splice(13,3,"L",a+c,e-6,a+c+6,e,a+c,e+6,a+c,b+d-f):h&&0>h&&e>b+g&&e<b+d-g?k.splice(33,3,"L",a,e+6,a-6,e,a,e-
			6,a,b+f):e&&e>d&&h>a+g&&h<a+c-g?k.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):e&&0>e&&h>a+g&&h<a+c-g&&k.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return k}},clipRect:function(a,b,c,d){var e="highcharts-"+Pa++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;a.count=0;return a},text:function(a,b,c,d){var e=ba||!S&&this.forExport,f={};if(d&&(this.allowHTML||!this.forExport))return this.html(a,b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));
		if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),p;for(p=0;p<d.length;p++)e=d[p],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,b){var c,d;a=a||this.style.fontSize;!a&&b&&K.getComputedStyle&&(b=b.element||b,a=(c=K.getComputedStyle(b,""))&&c.fontSize);a=/px/.test(a)?E(a):/em/.test(a)?12*parseFloat(a):12;c=24>a?a+3:C(1.2*
			a);d=C(.8*c);return{h:c,b:d,f:a}},rotCorr:function(a,b,c){var d=a;b&&c&&(d=w(d*ia(b*oa),4));return{x:-a/3*na(b*oa),y:d}},label:function(a,b,c,d,e,f,g,h,k){function m(){var a,b;a=x.element.style;r=(void 0===O||void 0===la||n.styles.textAlign)&&v(x.textStr)&&x.getBBox();n.width=(O||r.width||0)+2*H+w;n.height=(la||r.height||0)+2*H;I=H+p.fontMetrics(a&&a.fontSize,x).b;K&&(u||(a=C(-A*H)+E,b=(h?-I:0)+E,n.box=u=d?p.symbol(d,a,b,n.width,n.height,G):p.rect(a,b,n.width,n.height,0,G["stroke-width"]),u.isImg||
	u.attr("fill","none"),u.add(n)),u.isImg||u.attr(B({width:C(n.width),height:C(n.height)},G)),G=null)}function l(){var a=n.styles,a=a&&a.textAlign,b=w+H*(1-A),c;c=h?0:I;v(O)&&r&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(O-r.width));if(b!==x.x||c!==x.y)x.attr("x",b),c!==y&&x.attr("y",c);x.x=b;x.y=c}function q(a,b){u?u.attr(a,b):G[a]=b}var p=this,n=p.g(k),x=p.text("",0,0,g).attr({zIndex:1}),u,r,A=0,H=3,w=0,O,la,z,F,E=0,G={},I,K;n.onAdd=function(){x.add(n);n.attr({text:a||0===a?a:"",x:b,
		y:c});u&&v(e)&&n.attr({anchorX:e,anchorY:f})};n.widthSetter=function(a){O=a};n.heightSetter=function(a){la=a};n.paddingSetter=function(a){v(a)&&a!==H&&(H=n.padding=a,l())};n.paddingLeftSetter=function(a){v(a)&&a!==w&&(w=a,l())};n.alignSetter=function(a){A={left:0,center:.5,right:1}[a]};n.textSetter=function(a){a!==y&&x.textSetter(a);m();l()};n["stroke-widthSetter"]=function(a,b){a&&(K=!0);E=a%2/2;q(b,a)};n.strokeSetter=n.fillSetter=n.rSetter=function(a,b){"fill"===b&&a&&(K=!0);q(b,a)};n.anchorXSetter=
			function(a,b){e=a;q(b,C(a)-E-z)};n.anchorYSetter=function(a,b){f=a;q(b,a-F)};n.xSetter=function(a){n.x=a;A&&(a-=A*((O||r.width)+H));z=C(a);n.attr("translateX",z)};n.ySetter=function(a){F=n.y=C(a);n.attr("translateY",F)};var L=n.css;return B(n,{css:function(a){if(a){var b={};a=D(a);t(n.textProps,function(c){a[c]!==y&&(b[c]=a[c],delete a[c])});x.css(b)}return L.call(n,a)},getBBox:function(){return{width:r.width+2*H,height:r.height+2*H,x:r.x-H,y:r.y-H}},shadow:function(a){u&&u.shadow(a);return n},destroy:function(){W(n.element,
			"mouseenter");W(n.element,"mouseleave");x&&(x=x.destroy());u&&(u=u.destroy());M.prototype.destroy.call(n);n=p=m=l=q=null}})}};ma.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.categories,e=a.names,f=this.pos,g=b.labels,h=a.tickPositions,k=f===h[0],m=f===h[h.length-1],e=d?r(d[f],e[f],f):f,d=this.label,h=h.info,l;a.isDatetimeAxis&&h&&(l=b.dateTimeLabelFormats[h.higherRanks[f]||h.unitName]);this.isFirst=k;this.isLast=m;b=a.labelFormatter.call({axis:a,chart:c,isFirst:k,isLast:m,
	dateTimeLabelFormat:l,value:a.isLog?Z(ea(e)):e});v(d)?d&&d.attr({text:b}):(this.labelLength=(this.label=d=v(b)&&g.enabled?c.renderer.text(b,0,0,g.useHTML).css(D(g.style)).add(a.labelGroup):null)&&d.getBBox().width,this.rotation=0)},getLabelSize:function(){return this.label?this.label.getBBox()[this.axis.horiz?"height":"width"]:0},handleOverflow:function(a){var b=this.axis,c=a.x,d=b.chart.chartWidth,e=b.chart.spacing,f=r(b.labelLeft,G(b.pos,e[3])),e=r(b.labelRight,w(b.pos+b.len,d-e[1])),g=this.label,
		h=this.rotation,k={left:0,center:.5,right:1}[b.labelAlign],m=g.getBBox().width,l=b.slotWidth,q=1,p,n={};if(h)0>h&&c-k*m<f?p=C(c/ia(h*oa)-f):0<h&&c+k*m>e&&(p=C((d-c)/ia(h*oa)));else if(d=c+(1-k)*m,c-k*m<f?l=a.x+l*(1-k)-f:d>e&&(l=e-a.x+l*k,q=-1),l=G(b.slotWidth,l),l<b.slotWidth&&"center"===b.labelAlign&&(a.x+=q*(b.slotWidth-l-k*(b.slotWidth-G(m,l)))),m>l||b.autoRotation&&g.styles.width)p=l;p&&(n.width=p,b.options.labels.style.textOverflow||(n.textOverflow="ellipsis"),g.css(n))},getPosition:function(a,
		b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,m=k.transA,l=k.reversed,q=k.staggerLines,p=k.tickRotCorr||{x:0,y:0};c=r(e.y,p.y+(2===k.side?8:-(c.getBBox().height/2)));a=a+e.x+p.x-(f&&d?f*m*(l?-1:1):0);
	b=b+c-(f&&!d?f*m*(l?1:-1):0);q&&(b+=g/(h||1)%q*(k.labelOffset/q));return{x:a,y:C(b)}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,m=this.pos,l=e.labels,q=this.gridLine,p=h?h+"Grid":"grid",n=h?h+"Tick":"tick",x=e[p+"LineWidth"],u=e[p+"LineColor"],t=e[p+"LineDashStyle"],A=e[n+"Length"],p=r(e[n+"Width"],!h&&d.isXAxis?1:0),v=e[n+"Color"],w=e[n+"Position"],
		n=this.mark,O=l.step,la=!0,C=d.tickmarkOffset,z=this.getPosition(g,m,C,b),B=z.x,z=z.y,D=g&&B===d.pos+d.len||!g&&z===d.pos?-1:1;c=r(c,1);this.isActive=!0;if(x&&(m=d.getPlotLinePath(m+C,x*D,b,!0),q===y&&(q={stroke:u,"stroke-width":x},t&&(q.dashstyle=t),h||(q.zIndex=1),b&&(q.opacity=0),this.gridLine=q=x?f.path(m).attr(q).add(d.gridGroup):null),!b&&q&&m))q[this.isNew?"attr":"animate"]({d:m,opacity:c});p&&A&&("inside"===w&&(A=-A),d.opposite&&(A=-A),h=this.getMarkPath(B,z,A,p*D,g,f),n?n.animate({d:h,opacity:c}):
		this.mark=f.path(h).attr({stroke:v,"stroke-width":p,opacity:c}).add(d.axisGroup));k&&!isNaN(B)&&(k.xy=z=this.getLabelPosition(B,z,k,g,l,C,a,O),this.isFirst&&!this.isLast&&!r(e.showFirstLabel,1)||this.isLast&&!this.isFirst&&!r(e.showLastLabel,1)?la=!1:!g||d.isRadial||l.step||l.rotation||b||0===c||this.handleOverflow(z),O&&a%O&&(la=!1),la&&!isNaN(z.y)?(z.opacity=c,k[this.isNew?"attr":"animate"](z),this.isNew=!1):k.attr("y",-9999))},destroy:function(){Aa(this,this.axis)}};var Sa=z.Axis=function(){this.init.apply(this,
		arguments)};Sa.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#D8D8D8",labels:{enabled:!0,style:{color:"#606060",cursor:"default",fontSize:"11px"},x:0,y:15},lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,
	startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",title:{align:"middle",style:{color:"#707070"}},type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:.05,minPadding:.05,startOnTick:!0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return z.numberFormat(this.total,-1)},style:D(Ga.line.dataLabels.style,{color:"#000000"})}},
	defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{autoRotation:[-45],x:0,y:null},title:{rotation:0}},defaultTopAxisOptions:{labels:{autoRotation:[-45],x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.chart=a;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?
					1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.reversed=d.reversed;this.visible=!1!==d.visible;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=d.categories||"category"===e;this.names=this.names||[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=v(d.linkedTo);this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands=
	{};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.stacksTouched=0;this.min=this.max=null;this.crosshair=r(d.crosshair,ra(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===qb(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===y&&(this.reversed=!0);this.removePlotLine=
			this.removePlotBand=this.removePlotBandOrLine;for(f in d)P(this,f,d[f]);this.isLog&&(this.val2lin=Ja,this.lin2val=ea)},setOptions:function(a){this.options=D(this.defaultOptions,this.isXAxis?{}:this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],D(L[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=L.lang.numericSymbols,f=e&&e.length,
			g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=xa(h,this);else if(c)g=b;else if(d)g=ya(d,b);else if(f&&1E3<=a)for(;f--&&g===y;)c=Math.pow(1E3,f+1),a>=c&&0===10*b%c&&null!==e[f]&&(g=z.numberFormat(b/c,-1)+e[f]);g===y&&(g=1E4<=V(b)?z.numberFormat(b,-1):z.numberFormat(b,-1,y,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.threshold=null;a.softThreshold=!a.isXAxis;a.buildStacks&&a.buildStacks();t(a.series,function(c){if(c.visible||
			!b.options.chart.ignoreHiddenSeries){var d=c.options,e=d.threshold,f;a.hasVisibleSeries=!0;a.isLog&&0>=e&&(e=null);if(a.isXAxis)d=c.xData,d.length&&(a.dataMin=G(r(a.dataMin,d[0]),za(d)),a.dataMax=w(r(a.dataMax,d[0]),ta(d)));else if(c.getExtremes(),f=c.dataMax,c=c.dataMin,v(c)&&v(f)&&(a.dataMin=G(r(a.dataMin,c),c),a.dataMax=w(r(a.dataMax,f),f)),v(e)&&(a.threshold=e),!d.softThreshold||a.isLog)a.softThreshold=!1}})},translate:function(a,b,c,d,e,f){var g=this.linkedParent||this,h=1,k=0,m=d?g.oldTransA:
			g.transA;d=d?g.oldMin:g.min;var l=g.minPixelPadding;e=(g.doPostTranslate||g.isLog&&e)&&g.lin2val;m||(m=g.transA);c&&(h*=-1,k=g.len);g.reversed&&(h*=-1,k-=h*(g.sector||g.len));b?(a=a*h+k-l,a=a/m+d,e&&(a=g.lin2val(a))):(e&&(a=g.val2lin(a)),"between"===f&&(f=.5),a=h*(a-d)*m+k+h*l+(ga(f)?m*f*g.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,
			b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,m,l=c&&f.oldChartHeight||f.chartHeight,q=c&&f.oldChartWidth||f.chartWidth,p;k=this.transB;var n=function(a,b,c){if(a<b||a>c)d?a=G(w(b,a),c):p=!0;return a};e=r(e,this.translate(a,null,null,c));a=c=C(e+k);k=m=C(l-e-k);isNaN(e)?p=!0:this.horiz?(k=h,m=l-this.bottom,a=c=n(a,g,g+this.width)):(a=g,c=q-this.right,k=m=n(k,h,h+this.height));return p&&!d?null:f.renderer.crispLine(["M",a,k,"L",c,m],b||1)},getLinearTickPositions:function(a,b,c){var d,e=Z(U(b/
					a)*a),f=Z(aa(c/a)*a),g=[];if(b===c&&ga(b))return[b];for(b=e;b<=f;){g.push(b);b=Z(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e,f=this.pointRangePadding||0;e=this.min-f;var f=this.max+f,g=f-e;if(g&&g/c<this.len/3)if(this.isLog)for(f=b.length,e=1;e<f;e++)d=d.concat(this.getLogTickPositions(c,b[e-1],b[e],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),
			e,f,a.startOfWeek));else for(b=e+(b[0]-e)%c;b<=f;b+=c)d.push(b);0!==d.length&&this.trimTicks(d,a.startOnTick,a.endOnTick);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,m,l;this.isXAxis&&this.minRange===y&&!this.isLog&&(v(a.min)||v(a.max)?this.minRange=null:(t(this.series,function(a){k=a.xData;for(g=m=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===y||h<f)f=h}),this.minRange=G(5*f,this.dataMax-this.dataMin)));
		c-b<this.minRange&&(l=this.minRange,d=(l-c+b)/2,d=[b-d,r(a.min,b-d)],e&&(d[2]=this.dataMin),b=ta(d),c=[b+l,r(a.max,b+l)],e&&(c[2]=this.dataMax),c=za(c),c-b<l&&(d[0]=c-l,d[1]=r(a.min,c-l),b=ta(d)));this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,m=b.transA,l=b.isXAxis;if(l||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):t(b.series,function(a){var c=k?1:l?a.pointRange:b.axisPointRange||0,h=a.options.pointPlacement,
			m=a.closestPointRange;d=w(d,c);b.single||(f=w(f,ca(h)?0:c/2),g=w(g,"on"===h?0:c));!a.noSharedTooltip&&v(m)&&(e=v(e)?G(e,m):m)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=G(d,c),l&&(b.closestPointRange=e);a&&(b.oldTransA=m);b.translationSlope=b.transA=m=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=m*f},minFromRange:function(){return this.max-this.range},setTickInterval:function(a){var b=this,c=b.chart,d=b.options,e=b.isLog,
			f=b.isDatetimeAxis,g=b.isXAxis,h=b.isLinked,k=d.maxPadding,m=d.minPadding,l=d.tickInterval,q=d.tickPixelInterval,p=b.categories,n=b.threshold,x=b.softThreshold,u,J,A,H;f||p||h||this.getTickAmount();A=r(b.userMin,d.min);H=r(b.userMax,d.max);h?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=r(c.min,c.dataMin),b.max=r(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&T(11,1)):(!x&&v(n)&&(b.dataMin>=n?(u=n,m=0):b.dataMax<=n&&(J=n,k=0)),b.min=r(A,u,b.dataMin),b.max=r(H,
			J,b.dataMax));e&&(!a&&0>=G(b.min,r(b.dataMin,b.min))&&T(10,1),b.min=Z(Ja(b.min),15),b.max=Z(Ja(b.max),15));b.range&&v(b.max)&&(b.userMin=b.min=A=w(b.min,b.minFromRange()),b.userMax=H=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(p||b.axisPointRange||b.usePercentage||h)&&v(b.min)&&v(b.max)&&(c=b.max-b.min)&&(!v(A)&&m&&(b.min-=c*m),!v(H)&&k&&(b.max+=c*k));ga(d.floor)&&(b.min=w(b.min,d.floor));ga(d.ceiling)&&(b.max=G(b.max,d.ceiling));x&&v(b.dataMin)&&(n=n||0,!v(A)&&
	b.min<n&&b.dataMin>=n?b.min=n:!v(H)&&b.max>n&&b.dataMax<=n&&(b.max=n));b.tickInterval=b.min===b.max||void 0===b.min||void 0===b.max?1:h&&!l&&q===b.linkedParent.options.tickPixelInterval?l=b.linkedParent.tickInterval:r(l,this.tickAmount?(b.max-b.min)/w(this.tickAmount-1,1):void 0,p?1:(b.max-b.min)*q/w(b.len,q));g&&!a&&t(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=
			b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=w(b.pointRange,b.tickInterval));a=r(d.minTickInterval,b.isDatetimeAxis&&b.closestPointRange);!l&&b.tickInterval<a&&(b.tickInterval=a);f||e||l||(b.tickInterval=mb(b.tickInterval,null,N.pow(10,U(N.log(b.tickInterval)/N.LN10)),r(d.allowDecimals,!(.5<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max)),!!this.tickAmount));!this.tickAmount&&this.len&&(b.tickInterval=b.unsquish());this.setTickPositions()},setTickPositions:function(){var a=
			this.options,b,c=a.tickPositions,d=a.tickPositioner,e=a.startOnTick,f=a.endOnTick,g;this.tickmarkOffset=this.categories&&"between"===a.tickmarkPlacement&&1===this.tickInterval?.5:0;this.minorTickInterval="auto"===a.minorTickInterval&&this.tickInterval?this.tickInterval/5:a.minorTickInterval;this.tickPositions=b=c&&c.slice();!b&&(b=this.isDatetimeAxis?this.getTimeTicks(this.normalizeTimeTickInterval(this.tickInterval,a.units),this.min,this.max,a.startOfWeek,this.ordinalPositions,this.closestPointRange,
			!0):this.isLog?this.getLogTickPositions(this.tickInterval,this.min,this.max):this.getLinearTickPositions(this.tickInterval,this.min,this.max),b.length>this.len&&(b=[b[0],b.pop()]),this.tickPositions=b,d&&(d=d.apply(this,[this.min,this.max])))&&(this.tickPositions=b=d);this.isLinked||(this.trimTicks(b,e,f),this.min===this.max&&v(this.min)&&!this.tickAmount&&(g=!0,this.min-=.5,this.max+=.5),this.single=g,c||d||this.adjustTickAmount())},trimTicks:function(a,b,c){var d=a[0],e=a[a.length-1],f=this.minPointOffset||
			0;b?this.min=d:this.min-f>d&&a.shift();c?this.max=e:this.max+f<e&&a.pop();0===a.length&&v(d)&&a.push((e+d)/2)},getTickAmount:function(){var a={},b,c=this.options,d=c.tickAmount,e=c.tickPixelInterval;!v(c.tickInterval)&&this.len<e&&!this.isRadial&&!this.isLog&&c.startOnTick&&c.endOnTick&&(d=2);d||!1===this.chart.options.chart.alignTicks||!1===c.alignTicks||(t(this.chart[this.coll],function(c){var d=c.options,e=c.horiz,d=[e?d.left:d.top,e?d.width:d.height,d.pane].join();c.series.length&&(a[d]?b=!0:
			a[d]=1)}),b&&(d=aa(this.len/e)+1));4>d&&(this.finalTickAmt=d,d=5);this.tickAmount=d},adjustTickAmount:function(){var a=this.tickInterval,b=this.tickPositions,c=this.tickAmount,d=this.finalTickAmt,e=b&&b.length;if(e<c){for(;b.length<c;)b.push(Z(b[b.length-1]+a));this.transA*=(e-1)/(c-1);this.max=b[b.length-1]}else e>c&&(this.tickInterval*=2,this.setTickPositions());if(v(d)){for(a=c=b.length;a--;)(3===d&&1===a%2||2>=d&&0<a&&a<c-1)&&b.splice(a,1);this.finalTickAmt=y}},setScale:function(){var a,b;this.oldMin=
			this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();b=this.len!==this.oldAxisLength;t(this.series,function(b){if(b.isDirtyData||b.isDirty||b.xAxis.isDirty)a=!0});b||a||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax?(this.resetStacks&&this.resetStacks(),this.forceRedraw=!1,this.getSeriesExtremes(),this.setTickInterval(),this.oldUserMin=this.userMin,this.oldUserMax=this.userMax,this.isDirty||(this.isDirty=b||this.min!==this.oldMin||
			this.max!==this.oldMax)):this.cleanStacks&&this.cleanStacks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=r(c,!0);t(f.series,function(a){delete a.kdTree});e=B(e,{min:a,max:b});Q(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options,f=G(c,r(e.min,c)),e=w(d,r(e.max,d));this.allowZoomOutside||(v(c)&&a<=f&&(a=f),v(d)&&b>=e&&(b=e));this.displayBtn=a!==y||b!==y;this.setExtremes(a,b,!1,y,{trigger:"zoom"});
		return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=r(b.width,a.plotWidth-c+(b.offsetRight||0)),f=r(b.height,a.plotHeight),g=r(b.top,a.plotTop),b=r(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseFloat(f)/100*a.plotHeight);c.test(g)&&(g=parseFloat(g)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=w(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;
		return{min:a?Z(ea(this.min)):this.min,max:a?Z(ea(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?ea(this.min):this.min,b=b?ea(this.max):this.max;null===a?a=0>b?b:c:c>a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(r(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},unsquish:function(){var a=this.ticks,b=this.options.labels,c=this.horiz,
			d=this.tickInterval,e=d,f=this.len/(((this.categories?1:0)+this.max-this.min)/d),g,h=b.rotation,k=this.chart.renderer.fontMetrics(b.style.fontSize,a[0]&&a[0].label),m,l=Number.MAX_VALUE,q,p=function(a){a/=f||1;a=1<a?aa(a):1;return a*d};c?(q=!b.staggerLines&&!b.step&&(v(h)?[h]:f<r(b.autoRotationLimit,80)&&b.autoRotation))&&t(q,function(a){var b;if(a===h||a&&-90<=a&&90>=a)m=p(V(k.h/na(oa*a))),b=m+V(a/360),b<l&&(l=b,g=a,e=m)}):b.step||(e=p(k.h));this.autoRotation=q;this.labelRotation=r(g,h);return e},
	renderUnsquish:function(){var a=this.chart,b=a.renderer,c=this.tickPositions,d=this.ticks,e=this.options.labels,f=this.horiz,g=a.margin,h=this.categories?c.length:c.length-1,k=this.slotWidth=f&&!e.step&&!e.rotation&&(this.staggerLines||1)*a.plotWidth/h||!f&&(g[3]&&g[3]-a.spacing[3]||.33*a.chartWidth),m=w(1,C(k-2*(e.padding||5))),l={},g=b.fontMetrics(e.style.fontSize,d[0]&&d[0].label),h=e.style.textOverflow,q,p=0;ca(e.rotation)||(l.rotation=e.rotation||0);if(this.autoRotation)t(c,function(a){(a=d[a])&&
	a.labelLength>p&&(p=a.labelLength)}),p>m&&p>g.h?l.rotation=this.labelRotation:this.labelRotation=0;else if(k&&(q={width:m+"px"},!h))for(q.textOverflow="clip",k=c.length;!f&&k--;)if(m=c[k],m=d[m].label)"ellipsis"===m.styles.textOverflow&&m.css({textOverflow:"clip"}),m.getBBox().height>this.len/c.length-(g.h-g.f)&&(m.specCss={textOverflow:"ellipsis"});l.rotation&&(q={width:(p>.5*a.chartHeight?.33*a.chartHeight:a.chartHeight)+"px"},h||(q.textOverflow="ellipsis"));this.labelAlign=l.align=e.align||this.autoLabelAlign(this.labelRotation);
		t(c,function(a){var b=(a=d[a])&&a.label;b&&(b.attr(l),q&&b.css(D(q,b.specCss)),delete b.specCss,a.rotation=l.rotation)});this.tickRotCorr=b.rotCorr(g.b,this.labelRotation||0,2===this.side)},hasData:function(){return this.hasVisibleSeries||v(this.min)&&v(this.max)&&!!this.tickPositions},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,m,l,q=0,p,n=0,x=d.title,u=d.labels,J=0,A=b.axisOffset,b=b.clipOffset,H=[-1,
		1,1,-1][h],y,z=a.axisParent;m=a.hasData();a.showAxis=l=m||r(d.showEmpty,!0);a.staggerLines=a.horiz&&u.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(z),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(z),a.labelGroup=c.g("axis-labels").attr({zIndex:u.zIndex||7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add(z));if(m||a.isLinked)t(e,function(b){f[b]?f[b].addLabel():f[b]=new ma(a,b)}),a.renderUnsquish(),t(e,function(b){if(0===h||2===h||{1:"left",
				3:"right"}[h]===a.labelAlign)J=w(f[b].getLabelSize(),J)}),a.staggerLines&&(J*=a.staggerLines,a.labelOffset=J);else for(y in f)f[y].destroy(),delete f[y];x&&x.text&&!1!==x.enabled&&(a.axisTitle||(a.axisTitle=c.text(x.text,0,0,x.useHTML).attr({zIndex:7,rotation:x.rotation||0,align:x.textAlign||{low:"left",middle:"center",high:"right"}[x.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(x.style).add(a.axisGroup),a.axisTitle.isNew=!0),l&&(q=a.axisTitle.getBBox()[g?"height":"width"],
			p=x.offset,n=v(p)?0:r(x.margin,g?5:10)),a.axisTitle[l?"show":"hide"]());a.offset=H*r(d.offset,A[h]);a.tickRotCorr=a.tickRotCorr||{x:0,y:0};c=2===h?a.tickRotCorr.y:0;g=J+n+(J&&H*(g?r(u.y,a.tickRotCorr.y+8):u.x)-c);a.axisTitleMargin=r(p,g);A[h]=w(A[h],a.axisTitleMargin+q+H*a.offset,g);d=d.offset?0:2*U(d.lineWidth/2);b[k]=w(b[k],d)},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=
			-1);return b.renderer.crispLine(["M",e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,k=e.x||0,m=e.y||0,l=E(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?l:0);return{x:a?d+k:b+(g?this.width:0)+h+k,y:a?b+m-(g?this.height:
			0)+h:d+m}},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.isLog,f=a.isLinked,g=a.tickPositions,h=a.axisTitle,k=a.ticks,m=a.minorTicks,l=a.alternateBands,q=d.stackLabels,p=d.alternateGridColor,n=a.tickmarkOffset,r=d.lineWidth,u,w=b.hasRendered&&v(a.oldMin)&&!isNaN(a.oldMin),A=a.showAxis,H=c.globalAnimation,C,O;a.labelEdge.length=0;a.overlap=!1;t([k,m,l],function(a){for(var b in a)a[b].isActive=!1});if(a.hasData()||f)a.minorTickInterval&&!a.categories&&t(a.getMinorTickPositions(),
			function(b){m[b]||(m[b]=new ma(a,b,"minor"));w&&m[b].isNew&&m[b].render(null,!0);m[b].render(null,!1,1)}),g.length&&(t(g,function(b,c){if(!f||b>=a.min&&b<=a.max)k[b]||(k[b]=new ma(a,b)),w&&k[b].isNew&&k[b].render(c,!0,.1),k[b].render(c)}),n&&(0===a.min||a.single)&&(k[-1]||(k[-1]=new ma(a,-1,null,!0)),k[-1].render(-1))),p&&t(g,function(b,c){O=g[c+1]!==y?g[c+1]+n:a.max-n;0===c%2&&b<a.max&&O<=a.max-n&&(l[b]||(l[b]=new z.PlotLineOrBand(a)),C=b+n,l[b].options={from:e?ea(C):C,to:e?ea(O):O,color:p},l[b].render(),
			l[b].isActive=!0)}),a._addedPlotLB||(t((d.plotLines||[]).concat(d.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);t([k,m,l],function(a){var c,d,e=[],f=H?H.duration||500:0,g=function(){for(d=e.length;d--;)a[e[d]]&&!a[e[d]].isActive&&(a[e[d]].destroy(),delete a[e[d]])};for(c in a)a[c].isActive||(a[c].render(c,!1,0),a[c].isActive=!1,e.push(c));a!==l&&b.hasRendered&&f?f&&setTimeout(g,f):g()});r&&(u=a.getLinePath(r),a.axisLine?a.axisLine.animate({d:u}):a.axisLine=c.path(u).attr({stroke:d.lineColor,
		"stroke-width":r,zIndex:7}).add(a.axisGroup),a.axisLine[A?"show":"hide"]());h&&A&&(h[h.isNew?"attr":"animate"](a.getTitlePosition()),h.isNew=!1);q&&q.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.visible&&(this.render(),t(this.plotLinesAndBands,function(a){a.render()}));t(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||W(b);for(d in c)Aa(c[d]),c[d]=null;t([b.ticks,b.minorTicks,b.alternateBands],function(a){Aa(a)});
		for(a=e.length;a--;)e[a].destroy();t("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){var c,d=this.crosshair,e=d.animation;if(!this.crosshair||!1===(v(b)||!r(this.crosshair.snap,!0))||b&&b.series&&b.series[this.coll]!==this)this.hideCrosshair();else if(r(d.snap,!0)?v(b)&&(c=this.isXAxis?b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+
			this.pos,c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:r(b.stackY,b.y))||null:this.getPlotLinePath(null,null,null,null,c)||null,null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?"animate":"attr"]({d:c},e);else e=this.categories&&!this.isRadial,e={"stroke-width":d.width||(e?this.transA:1),stroke:d.color||(e?"rgba(155,200,255,0.2)":"#C0C0C0"),zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()},
	hideCrosshair:function(){this.cross&&this.cross.hide()}};B(Sa.prototype,void 0);var Ta=z.Legend=function(a,b){this.init(a,b)};Ta.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=b.itemMarginTop||0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=D(d,b.itemHiddenStyle),c.itemMarginTop=e,c.padding=d=r(b.padding,8),c.initialItemX=d,c.initialItemY=d-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.symbolWidth=r(b.symbolWidth,16),c.pages=[],c.render(),P(c.chart,"endResize",function(){c.positionCheckboxes()}))},
	colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,k={fill:h},m;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(m in k.stroke=h,g=a.convertAttribs(g),g)d=g[m],d!==y&&(k[m]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;(a=a.legendGroup)&&
	a.element&&a.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;t(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&Ba(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,t(this.allItems,function(e){var f=e.checkbox,g;f&&
	(g=c+f.y+(a||0)+3,R(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":"none"}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},setText:function(a){var b=this.options;
		a.legendItem.attr({text:b.labelFormat?xa(b.labelFormat,a):b.labelFormatter.call(a)})},renderItem:function(a){var b=this.chart,c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,k=this.itemHiddenStyle,m=this.padding,l=e?r(d.itemDistance,20):0,q=!d.rtl,p=d.width,n=d.itemMarginBottom||0,x=this.itemMarginTop,u=this.initialItemX,t=a.legendItem,A=a.series&&a.series.drawLegendSymbol?a.series:a,v=A.options,v=this.createCheckboxForItem&&v&&v.showCheckbox,
			y=d.useHTML;t||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=t=c.text("",q?f+g:-g,this.baseline||0,y).css(D(a.visible?h:k)).attr({align:q?"left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.fontMetrics=c.fontMetrics(h.fontSize,t),this.baseline=this.fontMetrics.f+3+x,t.attr("y",this.baseline)),A.drawLegendSymbol(this,a),this.setItemEvents&&this.setItemEvents(a,t,y,h,k),this.colorizeItem(a,a.visible),v&&this.createCheckboxForItem(a));this.setText(a);
		c=t.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+l+(v?20:0);this.itemHeight=g=C(a.legendItemHeight||c.height);e&&this.itemX-u+f>(p||b.chartWidth-2*m-u-d.x)&&(this.itemX=u,this.itemY+=x+this.lastLineHeight+n,this.lastLineHeight=0);this.maxItemWidth=w(this.maxItemWidth,f);this.lastItemY=x+this.itemY+n;this.lastLineHeight=w(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=x+g+n,this.lastLineHeight=g);this.offsetWidth=p||w((e?this.itemX-
						u-l:f)+m,this.offsetWidth)},getAllItems:function(){var a=[];t(this.chart.series,function(b){var c=b.options;r(c.showInLegend,v(c.linkedTo)?!1:y,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},adjustMargins:function(a,b){var c=this.chart,d=this.options,e=d.align.charAt(0)+d.verticalAlign.charAt(0)+d.layout.charAt(0);this.display&&!d.floating&&t([/(lth|ct|rth)/,/(rtv|rm|rbv)/,/(rbh|cb|lbh)/,/(lbv|lm|ltv)/],function(f,g){f.test(e)&&!v(a[g])&&(c[Da[g]]=w(c[Da[g]],c.legend[(g+
			1)%2?"legendHeight":"legendWidth"]+[1,-1,-1,1][g]*d[g%2?"x":"y"]+r(d.margin,12)+b[g]))})},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,k=a.box,m=a.options,l=a.padding,q=m.borderWidth,p=m.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();Ka(e,function(a,b){return(a.options&&
			a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});m.reversed&&e.reverse();a.allItems=e;a.display=f=!!e.length;a.lastLineHeight=0;t(e,function(b){a.renderItem(b)});g=(m.width||a.offsetWidth)+l;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);h+=l;if(q||p)k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,m.borderRadius,q||0).attr({stroke:m.borderColor,"stroke-width":q||0,fill:p||"none"}).add(d).shadow(m.shadow),
			k.isNew=!0),k[f?"show":"hide"]();a.legendWidth=g;a.legendHeight=h;t(e,function(b){a.positionItem(b)});f&&d.align(B({width:g,height:h},m),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,m=e.navigation,l=r(m.animation,!0),q=m.arrowSize||12,p=this.nav,n=this.pages,x=this.padding,u,v=this.allItems,A=function(a){k.attr({height:a});
		b.contentGroup.div&&(b.contentGroup.div.style.clip="rect("+x+"px,9999px,"+(x+a)+"px,0)")};"horizontal"===e.layout&&(f/=2);g&&(f=G(f,g));n.length=0;a>f?(this.clipHeight=h=w(f-20-this.titleHeight-x,0),this.currentPage=r(this.currentPage,1),this.fullHeight=a,t(v,function(a,b){var c=a._legendItemPos[1],d=C(a.legendItem.getBBox().height),e=n.length;if(!e||c-n[e-1]>h&&(u||c)!==n[e-1])n.push(u||c),e++;b===v.length-1&&c+d-n[e-1]>h&&n.push(c);c!==u&&(u=c)}),k||(k=b.clipRect=d.clipRect(0,x,9999,0),b.contentGroup.clip(k)),
			A(h),p||(this.nav=p=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",0,0,q,q).on("click",function(){b.scroll(-1,l)}).add(p),this.pager=d.text("",15,10).css(m.style).add(p),this.down=d.symbol("triangle-down",0,0,q,q).on("click",function(){b.scroll(1,l)}).add(p)),b.scroll(0),a=f):p&&(A(c.chartHeight),p.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,
			h=g.activeColor,g=g.inactiveColor,k=this.pager,m=this.padding;e>d&&(e=d);if(0<e){if(b!==y){var l=this.chart;l.renderer.globalAnimation=r(b,l.animation)}this.nav.attr({translateX:m,translateY:f+this.padding+7+this.titleHeight,visibility:"visible"});this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"});k.attr({text:e+"/"+d});this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"});c=-c[e-1]+this.initialItemY;this.scrollGroup.animate({translateY:c});
		this.currentPage=e;this.positionCheckboxes(c)}}};var vb=z.LegendSymbolMixin={drawRectangle:function(a,b){var c=a.options.symbolHeight||a.fontMetrics.f;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-c+1,a.symbolWidth,c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-C(.3*a.fontMetrics.b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&
(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(ja)||ua)&&hb(Ta.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});(z.Chart=function(){this.init.apply(this,arguments)}).prototype={callbacks:[],init:function(a,b){var c,d=a.series;a.series=null;c=D(L,a);c.series=a.series=
		d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=fa.length;fa.push(f);gb++;!1!==d.reflow&&P(f,"load",function(){f.initReflow()});if(e)for(g in e)P(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=ba?!1:r(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},
	initSeries:function(a){var b=this.options.chart;(b=va[a.type||b.type||b.defaultSeriesType])||T(17,!0);b=new b;b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,m=this.isDirtyBox,l=c.length,q=l,p=this.renderer,n=p.isHidden(),x=[];this.renderer.globalAnimation=r(a,this.animation);n&&this.cloneRenderTo();
		for(this.layOutTitles();q--;)if(a=c[q],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(q=l;q--;)a=c[q],a.options.stacking&&(a.isDirty=!0);t(c,function(a){a.isDirty&&"point"===a.options.legendType&&(a.updateTotals&&a.updateTotals(),f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();k&&!this.isResizing&&(this.maxTicks=null,t(b,function(a){a.setScale()}));this.getMargins();k&&(t(b,function(a){a.isDirty&&(m=!0)}),t(b,function(a){var b=a.min+","+a.max;a.extKey!==
		b&&(a.extKey=b,x.push(function(){Q(a,"afterSetExtremes",B(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(m||g)&&a.redraw()}));m&&this.drawChartBox();t(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);p.draw();Q(this,"redraw");n&&this.cloneRenderTo(!0);t(x,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<
	c.length;d++)for(e=c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=ra(b.xAxis||{}),b=b.yAxis=ra(b.yAxis||{});t(c,function(a,b){a.index=b;a.isX=!0});t(b,function(a,b){a.index=b});c=c.concat(b);t(c,function(b){new Sa(a,b)})},getSelectedPoints:function(){var a=[];t(this.series,function(b){a=a.concat(Ra(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return Ra(this.series,function(a){return a.selected})},
	setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=D(e.title,a);e=e.subtitle=D(e.subtitle,b);t([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-
			44;c&&(c.css({width:(f.width||h)+"px"}).align(B({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(B({y:b+(f.margin-13)+g.fontMetrics(e.style.fontSize,c).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=aa(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&r(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=
			this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;v(b)||(this.containerWidth=Fa(c,"width"));v(a)||(this.containerHeight=Fa(c,"height"));this.chartWidth=w(0,b||this.containerWidth||600);this.chartHeight=w(0,r(a,19<this.containerHeight?this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),Ba(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=
			b=this.renderTo.cloneNode(0),R(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),F.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options,c=b.chart,d,e,f;this.renderTo=a=c.renderTo;f="highcharts-"+Pa++;ca(a)&&(this.renderTo=a=F.getElementById(a));a||T(13,!0);d=E(I(a,"data-highcharts-chart"));!isNaN(d)&&fa[d]&&fa[d].hasRendered&&fa[d].destroy();I(a,"data-highcharts-chart",this.index);a.innerHTML=
			"";c.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();d=this.chartWidth;e=this.chartHeight;this.container=a=sa("div",{className:"highcharts-container"+(c.className?" "+c.className:""),id:f},B({position:"relative",overflow:"hidden",width:d+"px",height:e+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},c.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=new (z[c.renderer]||Ha)(a,d,e,c.style,c.forExport,b.exporting&&
			b.exporting.allowHTML);ba&&this.renderer.create(this,a,d,e);this.renderer.chartIndex=this.index},getMargins:function(a){var b=this.spacing,c=this.margin,d=this.titleOffset;this.resetMargins();d&&!v(c[0])&&(this.plotTop=w(this.plotTop,d+this.options.title.margin+b[0]));this.legend.adjustMargins(c,b);this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=this.extraTopMargin);a||this.getAxisMargins()},getAxisMargins:function(){var a=this,b=a.axisOffset=
			[0,0,0,0],c=a.margin;a.hasCartesianSeries&&t(a.axes,function(a){a.visible&&a.getOffset()});t(Da,function(d,e){v(c[e])||(a[d]+=b[e])});a.setChartSize()},reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Fa(d,"width"),f=c.height||Fa(d,"height"),c=a?a.target:K,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&!b.isPrinting&&e&&f&&(c===K||c===F)){if(e!==b.containerWidth||f!==b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,
			100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};P(K,"resize",b);P(a,"destroy",function(){W(K,"resize",b)})},setSize:function(a,b,c){var d=this,e,f,g,h=d.renderer;d.isResizing+=1;g=function(){d&&Q(d,"endResize",null,function(){--d.isResizing})};d.renderer.globalAnimation=r(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;v(a)&&(d.chartWidth=e=w(0,C(a)),d.hasUserSize=!!e);v(b)&&(d.chartHeight=f=w(0,C(b)));a=h.globalAnimation;
		(a?jb:R)(d.container,{width:e+"px",height:f+"px"},a);d.setChartSize(!0);h.setSize(e,f,c);d.maxTicks=null;t(d.axes,function(a){a.isDirty=!0;a.setScale()});t(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;Q(d,"resize");a=h.globalAnimation;!1===a?g():setTimeout(g,a&&a.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,g=this.spacing,
			h=this.clipOffset,k,m,l,q;this.plotLeft=k=C(this.plotLeft);this.plotTop=m=C(this.plotTop);this.plotWidth=l=w(0,C(d-k-this.marginRight));this.plotHeight=q=w(0,C(e-m-this.marginBottom));this.plotSizeX=b?q:l;this.plotSizeY=b?l:q;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:m,width:l,height:q};d=2*U(this.plotBorderWidth/2);b=aa(w(d,h[3])/2);c=aa(w(d,h[0])/2);this.clipBox={x:b,y:c,width:U(this.plotSizeX-
			w(d,h[1])/2-b),height:w(0,U(this.plotSizeY-w(d,h[2])/2-c))};a||t(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this;t(Da,function(b,c){a[b]=r(a.margin[c],a.spacing[c])});a.axisOffset=[0,0,0,0];a.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,m=a.backgroundColor,l=a.plotBackgroundColor,
			q=a.plotBackgroundImage,p=a.plotBorderWidth||0,n,r=this.plotLeft,u=this.plotTop,t=this.plotWidth,v=this.plotHeight,w=this.plotBox,y=this.clipRect,z=this.clipBox;n=k+(a.shadow?8:0);if(k||m)e?e.animate(e.crisp({width:c-n,height:d-n})):(e={fill:m||"none"},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(n/2,n/2,c-n,d-n,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));l&&(f?f.animate(w):this.plotBackground=b.rect(r,u,t,v,0).attr({fill:l}).add().shadow(a.plotShadow));
		q&&(h?h.animate(w):this.plotBGImage=b.image(q,r,u,t,v).add());y?y.animate({width:z.width,height:z.height}):this.clipRect=b.clipRect(z);p&&(g?g.animate(g.crisp({x:r,y:u,width:t,height:v,strokeWidth:-p})):this.plotBorder=b.rect(r,u,t,v,0,-p).attr({stroke:a.plotBorderColor,"stroke-width":p,fill:"none",zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,e,f;t(["inverted","angular","polar"],function(g){c=va[b.type||b.defaultSeriesType];f=a[g]||
			b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=va[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=this,b=a.series;t(b,function(a){a.linkedSeries.length=0});t(b,function(b){var d=b.options.linkedTo;ca(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d,b.visible=r(b.options.visible,d.options.visible,b.visible))})},renderSeries:function(){t(this.series,function(a){a.translate();a.render()})},renderLabels:function(){var a=this,
			b=a.options.labels;b.items&&t(b.items,function(c){var d=B(b.style,c.style),e=E(d.left)+a.plotLeft,f=E(d.top)+a.plotTop+12;delete d.left;delete d.top;a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options,d,e,f,g;this.setTitle();this.legend=new Ta(this,c.legend);this.getStacks&&this.getStacks();this.getMargins(!0);this.setChartSize();d=this.plotWidth;e=this.plotHeight-=13;t(a,function(a){a.setScale()});this.getAxisMargins();f=1.1<
			d/this.plotWidth;g=1.1<e/this.plotHeight;if(f||g)this.maxTicks=null,t(a,function(a){(a.horiz&&f||!a.horiz&&g)&&a.setTickInterval(!0)}),this.getMargins();this.drawChartBox();this.hasCartesianSeries&&t(a,function(a){a.visible&&a.render()});this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",
			function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;Q(a,"destroy");fa[a.index]=y;gb--;a.renderTo.removeAttribute("data-highcharts-chart");W(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();t("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),
			function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML="",W(d),f&&Ba(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!S&&K==K.top&&"complete"!==F.readyState||ba&&!K.canvg?(ba?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):F.attachEvent("onreadystatechange",function(){F.detachEvent("onreadystatechange",a.firstRender);"complete"===F.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;
		a.isReadyToRender()&&(a.getContainer(),Q(a,"init"),a.resetMargins(),a.setChartSize(),a.propFromSeries(),a.getAxes(),t(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),Q(a,"beforeRender"),z.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),t(a.callbacks,function(b){a.index!==y&&b.apply(a,[a])}),Q(a,"load"),a.cloneRenderTo(!0))},splashArray:function(a,b){var c=b[a],c=da(c)?c:[c,c,c,c];return[r(b[a+"Top"],c[0]),r(b[a+"Right"],c[1]),r(b[a+"Bottom"],c[2]),r(b[a+
	"Left"],c[3])]}};var Ia=function(){};Ia.prototype={init:function(a,b,c){this.series=a;this.color=a.color;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Ia.prototype.optionsToObject.call(this,a);B(this,a);this.options=this.options?
		B(this.options,a):a;d&&(this.y=this[d]);this.x===y&&c&&(this.x=b===y?c.autoIncrement():b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.options.keys,e=d||c.pointArrayMap||["y"],f=e.length,g=0,h=0;if("number"===typeof a||null===a)b[e[0]]=a;else if(pa(a))for(!d&&a.length>f&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),g++);h<f;)d&&void 0===a[g]||(b[e[h]]=a[g]),g++,h++;else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=
		!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),qa(b,this),b.length||(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)W(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a=["graphic","dataLabel","dataLabelUpper","connector","shadowGroup"],b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,
	y:this.y,color:this.color,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,d=r(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";t(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return xa(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;
	(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select&&d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});Q(this,a,b,c)},visible:!0};var lb=z.Series=function(){};lb.prototype={isCartesian:!0,type:"line",pointClass:Ia,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},directTouch:!1,axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x",
	"y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return r(a.options.index,a._i)-r(b.options.index,b._i)};c.chart=a;c.options=b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();B(c,{name:b.name,state:"",pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});ba&&(b.animation=!1);e=b.events;for(d in e)P(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();t(c.parallelArrays,function(a){c[a+"Data"]=
		[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;Ka(f,g);this.yAxis&&Ka(this.yAxis.series,g);t(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;t(a.axisTypes||[],function(e){t(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==y&&b[e]===d.id||b[e]===y&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||T(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,
		d=arguments;t(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=this.options,b=this.xIncrement,c,d=a.pointIntervalUnit,b=r(b,a.pointStart,0);this.pointInterval=c=r(this.pointInterval,a.pointInterval,1);if("month"===d||"year"===d)a=new La(b),a="month"===d?+a[ab](a[Na]()+c):+a[bb](a[Oa]()+c),c=a-b;this.xIncrement=b+c;return b},
	getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else t(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=D(e,c.series,a);this.tooltipOptions=D(L.tooltip,L.plotOptions[this.type].tooltip,
			b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;this.zoneAxis=c.zoneAxis;a=this.zones=(c.zones||[]).slice();!c.negativeColor&&!c.negativeFillColor||c.zones||a.push({value:c[this.zoneAxis+"Threshold"]||c.threshold||0,color:c.negativeColor,fillColor:c.negativeFillColor});a.length&&v(a[a.length-1].value)&&a.push({color:this.color,fillColor:this.fillColor});return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=
			a+"Counter";b||(v(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);this[a]=b},getColor:function(){this.options.colorByPoint?this.options.color=null:this.getCyclic("color",this.options.color||Ga[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:vb.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||
			0,h,k=e.options,m=e.chart,l=null,q=e.xAxis,p=q&&!!q.categories,n=k.turboThreshold,x=this.xData,u=this.yData,w=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=r(b,!0);if(!1!==d&&h&&g===h&&!e.cropped&&!e.hasGroupedData&&e.visible)t(a,function(a,b){f[b].update&&f[b].update(a,!1,null,!1)});else{e.xIncrement=null;e.pointRange=p?1:k.pointRange;e.colorCounter=0;t(this.parallelArrays,function(a){e[a+"Data"].length=0});if(n&&h>n){for(c=0;null===l&&c<h;)l=a[c],c++;if(ga(l)){p=r(k.pointStart,0);l=r(k.pointInterval,
			1);for(c=0;c<h;c++)x[c]=p,u[c]=a[c],p+=l;e.xIncrement=p}else if(pa(l))if(w)for(c=0;c<h;c++)l=a[c],x[c]=l[0],u[c]=l.slice(1,w+1);else for(c=0;c<h;c++)l=a[c],x[c]=l[0],u[c]=l[1];else T(12)}else for(c=0;c<h;c++)a[c]!==y&&(l={series:e},e.pointClass.prototype.applyOptions.apply(l,[a[c]]),e.updateParallelArrays(l,c),p&&v(l.name)&&(q.names[l.x]=l.name));ca(u[0])&&T(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();q&&(q.minRange=q.userMinRange);e.isDirty=e.isDirtyData=m.isDirtyBox=
			!0;c=!1}"point"===k.legendType&&(this.processData(),this.generatePoints());b&&m.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,e;e=0;var f,g,h=this.xAxis,k,m=this.options;k=m.cropThreshold;var l=this.getExtremesFromAll||m.getExtremesFromAll,q=this.isCartesian,p,n;if(q&&!this.isDirty&&!h.isDirty&&!this.yAxis.isDirty&&!a)return!1;h&&(a=h.getExtremes(),p=a.min,n=a.max);if(q&&this.sorted&&!l&&(!k||d>k||this.forceCrop))if(b[d-1]<p||b[0]>n)b=[],c=[];else if(b[0]<p||b[d-1]>n)e=
			this.cropData(this.xData,this.yData,p,n),b=e.xData,c=e.yData,e=e.start,f=!0;for(k=b.length-1;0<=k;k--)d=b[k]-b[k-1],0<d&&(g===y||d<g)?g=d:0>d&&this.requireSorting&&T(15);this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;null===m.pointRange&&(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=r(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=w(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,
			g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,k,m=this.hasGroupedData,l,q=[],p;b||m||(b=[],b.length=a.length,b=this.data=b);for(p=0;p<g;p++)k=h+p,m?q[p]=(new f).init(this,[d[p]].concat(ra(e[p]))):(b[k]?l=b[k]:a[k]!==y&&(b[k]=l=(new f).init(this,a[k],d[p])),q[p]=l),q[p].index=k;if(b&&(g!==(c=b.length)||m))for(p=0;p<c;p++)p!==h||m||(p+=g),b[p]&&(b[p].destroyElements(),b[p].plotX=
			y);this.data=b;this.points=q},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=d.min,h=d.max,k,m,l,q;a=a||this.stackedYData||this.processedYData;d=a.length;for(q=0;q<d;q++)if(m=c[q],l=a[q],k=null!==l&&l!==y&&(!b.isLog||l.length||0<l),m=this.getExtremesFromAll||this.options.getExtremesFromAll||this.cropped||(c[q+1]||m)>=g&&(c[q-1]||m)<=h,k&&m)if(k=l.length)for(;k--;)null!==l[k]&&(e[f++]=l[k]);else e[f++]=l;this.dataMin=za(e);this.dataMax=ta(e)},
	translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,m="between"===k||ga(k),l=a.threshold,q=a.startFromThreshold?l:0,p,n,t,u,z=Number.MAX_VALUE,a=0;a<g;a++){var A=f[a],C=A.x,B=A.y;n=A.low;var D=b&&e.stacks[(this.negStacks&&B<(q?0:l)?"-":"")+this.stackKey];e.isLog&&null!==B&&0>=B&&(A.y=B=null,T(10));A.plotX=p=G(w(-1E5,c.translate(C,
			0,0,0,1,k,"flags"===this.type)),1E5);b&&this.visible&&D&&D[C]&&(u=this.getStackIndicator(u,C,this.index),D=D[C],B=D.points[u.key],n=B[0],B=B[1],n===q&&(n=r(l,e.min)),e.isLog&&0>=n&&(n=null),A.total=A.stackTotal=D.total,A.percentage=D.total&&A.y/D.total*100,A.stackY=B,D.setOffset(this.pointXOffset||0,this.barW||0));A.yBottom=v(n)?e.translate(n,0,1,0,1):null;h&&(B=this.modifyValue(B,A));A.plotY=n="number"===typeof B&&Infinity!==B?G(w(-1E5,e.translate(B,0,1,0,1)),1E5):y;A.isInside=n!==y&&0<=n&&n<=e.len&&
			0<=p&&p<=c.len;A.clientX=m?c.translate(C,0,0,0,1):p;A.negative=A.y<(l||0);A.category=d&&d[A.x]!==y?d[A.x]:A.x;a&&(z=G(z,V(p-t)));t=p}this.closestPointRangePx=z;this.getSegments()},setClip:function(a){var b=this.chart,c=this.options,d=b.renderer,e=b.inverted,f=this.clipBox,g=f||b.clipBox,h=this.sharedClipKey||["_sharedClip",a&&a.duration,a&&a.easing,g.height,c.xAxis,c.yAxis].join(),k=b[h],m=b[h+"m"];k||(a&&(g.width=0,b[h+"m"]=m=d.clipRect(-99,e?-b.plotLeft:-b.plotTop,99,e?b.chartWidth:b.chartHeight)),
			b[h]=k=d.clipRect(g));a&&(k.count+=1);!1!==c.clip&&(this.group.clip(a||f?k:b.clipRect),this.markerGroup.clip(m),this.sharedClipKey=h);a||(--k.count,0>=k.count&&h&&b[h]&&(f||(b[h]=b[h].destroy()),b[h+"m"]&&(b[h+"m"]=b[h+"m"].destroy())))},animate:function(a){var b=this.chart,c=this.options.animation,d;c&&!da(c)&&(c=Ga[this.type].animation);a?this.setClip(c):(d=this.sharedClipKey,(a=b[d])&&a.animate({width:b.plotSizeX},c),b[d+"m"]&&b[d+"m"].animate({width:b.plotSizeX+99},c),this.animate=null)},afterAnimate:function(){this.setClip();
		Q(this,"afterAnimate")},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,k,m,l,q=this.options.marker,p=this.pointAttr[""],n,t,u,v=this.markerGroup,w=r(q.enabled,this.xAxis.isRadial,this.closestPointRangePx>2*q.radius);if(!1!==q.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=U(g.plotX),e=g.plotY,l=g.graphic,n=g.marker||{},t=!!g.marker,a=w&&n.enabled===y||n.enabled,u=g.isInside,a&&e!==y&&!isNaN(e)&&null!==g.y?(a=g.pointAttr[g.selected?"select":""]||p,h=a.r,k=r(n.symbol,
			this.symbol),m=0===k.indexOf("url"),l?l[u?"show":"hide"](!0).animate(B({x:d-h,y:e-h},l.symbolName?{width:2*h,height:2*h}:{})):u&&(0<h||m)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h,t?n:q).attr(a).add(v))):l&&(g.graphic=l.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e)g=e[f],h[f]=r(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,c=Ga[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color,
			h=a.options.negativeColor;f={stroke:g,fill:g};var k=a.points||[],m,l,q=[],p=a.pointAttrToOptions;m=a.hasPointSpecificOptions;var n=c.lineColor,x=c.fillColor;l=b.turboThreshold;var u=a.zones,w=a.zoneAxis||"y",y;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):(e.color=e.color||ka(e.color||g).brighten(e.brightness).get(),e.negativeColor=e.negativeColor||ka(e.negativeColor||h).brighten(e.brightness).get());q[""]=a.convertAttribs(c,f);t(["hover",
		"select"],function(b){q[b]=a.convertAttribs(d[b],q[""])});a.pointAttr=q;g=k.length;if(!l||g<l||m)for(;g--;){l=k[g];(c=l.options&&l.options.marker||l.options)&&!1===c.enabled&&(c.radius=0);if(u.length){m=0;for(f=u[m];l[w]>=f.value;)f=u[++m];l.color=l.fillColor=r(f.color,a.color)}m=b.colorByPoint||l.color;if(l.options)for(y in p)v(c[p[y]])&&(m=!0);if(m){c=c||{};m=[];d=c.states||{};f=d.hover=d.hover||{};if(!b.marker||l.negative&&!f.fillColor&&!e.fillColor)f[a.pointAttrToOptions.fill]=f.color||!l.options.color&&
			e[l.negative&&h?"negativeColor":"color"]||ka(l.color).brighten(f.brightness||e.brightness).get();f={color:l.color};x||(f.fillColor=l.color);n||(f.lineColor=l.color);c.hasOwnProperty("color")&&!c.color&&delete c.color;m[""]=a.convertAttribs(B(f,c),q[""]);m.hover=a.convertAttribs(d.hover,q.hover,m[""]);m.select=a.convertAttribs(d.select,q.select,m[""])}else m=q;l.pointAttr=m}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(ja),d,e=a.data||[],f,g,h;Q(a,"destroy");W(a);t(a.axisTypes||
			[],function(b){if(h=a[b])qa(h.series,a),h.isDirty=h.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(d=e.length;d--;)(f=e[d])&&f.destroy&&f.destroy();a.points=null;clearTimeout(a.animationTimeout);for(g in a)a[g]instanceof M&&!a[g].survive&&(d=c&&"group"===g?"hide":"destroy",a[g][d]());b.hoverSeries===a&&(b.hoverSeries=null);qa(b.series,a);for(g in a)delete a[g]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;t(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?
			c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],"right"===d?c.push(k.plotX,h,"L"):"center"===d?c.push((k.plotX+g)/2,k.plotY,"L",(k.plotX+g)/2,h,"L"):c.push(g,k.plotY,"L")),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=this,b=[],c,d=[];t(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color,b.dashStyle]],
			d=b.lineWidth,e="square"!==b.linecap,f=this.getGraphPath(),g=this.fillGraph&&this.color||"none";t(this.zones,function(d,e){c.push(["zoneGraph"+e,d.color||a.color,d.dashStyle||b.dashStyle])});t(c,function(c,k){var m=c[0],l=a[m];l?l.animate({d:f}):(d||g)&&f.length&&(l={stroke:c[1],"stroke-width":d,fill:g,zIndex:1},c[2]?l.dashstyle=c[2]:e&&(l["stroke-linecap"]=l["stroke-linejoin"]="round"),a[m]=a.chart.renderer.path(f).attr(l).add(a.group).shadow(2>k&&b.shadow))})},applyZones:function(){var a=this,b=
			this.chart,c=b.renderer,d=this.zones,e,f,g=this.clips||[],h,k=this.graph,m=this.area,l=w(b.chartWidth,b.chartHeight),q=this[(this.zoneAxis||"y")+"Axis"],p,n=q.reversed,v=b.inverted,u=q.horiz,z,A,B,D=!1;d.length&&(k||m)&&q.min!==y&&(k&&k.hide(),m&&m.hide(),p=q.getExtremes(),t(d,function(d,t){e=n?u?b.plotWidth:0:u?0:q.toPixels(p.min);e=G(w(r(f,e),0),l);f=G(w(C(q.toPixels(r(d.value,p.max),!0)),0),l);D&&(e=f=q.toPixels(p.max));z=Math.abs(e-f);A=G(e,f);B=w(e,f);q.isXAxis?(h={x:v?B:A,y:0,width:z,height:l},
	u||(h.x=b.plotHeight-h.x)):(h={x:0,y:v?B:A,width:l,height:z},u&&(h.y=b.plotWidth-h.y));b.inverted&&c.isVML&&(h=q.isXAxis?{x:0,y:n?A:B,height:h.width,width:b.chartWidth}:{x:h.y-b.plotLeft-b.spacingBox.x,y:0,width:h.height,height:b.chartHeight});g[t]?g[t].animate(h):(g[t]=c.clipRect(h),k&&a["zoneGraph"+t].clip(g[t]),m&&a["zoneArea"+t].clip(g[t]));D=d.value>p.max}),this.clips=g)},invertGroups:function(){function a(){var a={width:b.yAxis.len,height:b.xAxis.len};t(["group","markerGroup"],function(c){b[c]&&
	b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(P(c,"resize",a),P(b,"destroy",function(){W(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e),f.addClass("highcharts-series-"+this.index));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?b.left:a.plotLeft,translateY:c?
			c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&b.renderer.isSVG&&r(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.applyZones());t(a.points,function(a){a.redraw&&a.redraw()});a.drawDataLabels&&
	a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.isDirty,d=this.group,e=this.xAxis,f=this.yAxis;d&&(a.inverted&&d.attr({width:a.plotWidth,height:a.plotHeight}),
			d.animate({translateX:r(e&&e.left,a.plotLeft),translateY:r(f&&f.top,a.plotTop)}));this.translate();this.render();b&&Q(this,"updatedData");(c||b)&&delete this.kdTree},kdDimensions:1,kdAxisArray:["clientX","plotY"],searchPoint:function(a,b){var c=this.xAxis,d=this.yAxis,e=this.chart.inverted;return this.searchKDTree({clientX:e?c.len-a.chartY+c.pos:a.chartX-c.pos,plotY:e?d.len-a.chartX+d.pos:a.chartY-d.pos},b)},buildKDTree:function(){function a(b,d,g){var h,k;if(k=b&&b.length)return h=c.kdAxisArray[d%
	g],b.sort(function(a,b){return a[h]-b[h]}),k=Math.floor(k/2),{point:b[k],left:a(b.slice(0,k),d+1,g),right:a(b.slice(k+1),d+1,g)}}function b(){var b=Ra(c.points||[],function(a){return null!==a.y});c.kdTree=a(b,d,d)}var c=this,d=c.kdDimensions;delete c.kdTree;c.options.kdSync?b():setTimeout(b)},searchKDTree:function(a,b){function c(a,b,m,l){var q=b.point,p=d.kdAxisArray[m%l],n,r,t=q;r=v(a[e])&&v(q[e])?Math.pow(a[e]-q[e],2):null;n=v(a[f])&&v(q[f])?Math.pow(a[f]-q[f],2):null;n=(r||0)+(n||0);q.dist=v(n)?
			Math.sqrt(n):Number.MAX_VALUE;q.distX=v(r)?Math.sqrt(r):Number.MAX_VALUE;p=a[p]-q[p];n=0>p?"left":"right";r=0>p?"right":"left";b[n]&&(n=c(a,b[n],m+1,l),t=n[g]<t[g]?n:q);b[r]&&Math.sqrt(p*p)<t[g]&&(a=c(a,b[r],m+1,l),t=a[g]<t[g]?a:t);return t}var d=this,e=this.kdAxisArray[0],f=this.kdAxisArray[1],g=b?"distX":"dist";this.kdTree||this.buildKDTree();if(this.kdTree)return c(a,this.kdTree,this.kdDimensions,this.kdDimensions)}};var wb=Ua(lb);va.line=wb;B(z,{Color:ka,Point:Ia,Tick:ma,Renderer:Ha,SVGElement:M,
	SVGRenderer:Ha,arrayMin:za,arrayMax:ta,charts:fa,dateFormat:ya,error:T,format:xa,pathAnim:Qa,getOptions:function(){return L},hasBidiBug:ob,isTouchDevice:eb,setOptions:function(a){L=D(!0,L,a);Va();return L},addEvent:P,removeEvent:W,createElement:sa,discardElement:Ba,css:R,each:t,map:ib,merge:D,splat:ra,extendClass:Ua,pInt:E,svg:S,canvas:ba,vml:!S&&!ba,product:"Highcharts 4.1.9",version:"/Highstock 2.1.9"})})();

if(console&&(typeof console.log!='object'))console.log('HighCharts library initialized in:',(window.anychart_init_start=(typeof window.performance=='object')&&(typeof window.performance.now=='function')?window.performance.now():+new Date()-window.highcharts_init_start).toFixed(5),'ms');delete window.highcharts_init_start