goog.provide('anychart.exports.ElementsTextMarker');
goog.require('anychart.elements.TextMarker');

goog.exportSymbol('anychart.elements.TextMarker', anychart.elements.TextMarker);
anychart.elements.TextMarker.prototype['value'] = anychart.elements.TextMarker.prototype.value;
anychart.elements.TextMarker.prototype['scale'] = anychart.elements.TextMarker.prototype.scale;
anychart.elements.TextMarker.prototype['parentBounds'] = anychart.elements.TextMarker.prototype.parentBounds;
anychart.elements.TextMarker.prototype['anchor'] = anychart.elements.TextMarker.prototype.anchor;
anychart.elements.TextMarker.prototype['align'] = anychart.elements.TextMarker.prototype.align;
anychart.elements.TextMarker.prototype['direction'] = anychart.elements.TextMarker.prototype.direction;
anychart.elements.TextMarker.prototype['offsetX'] = anychart.elements.TextMarker.prototype.offsetX;
anychart.elements.TextMarker.prototype['offsetY'] = anychart.elements.TextMarker.prototype.offsetY;
anychart.elements.TextMarker.prototype['text'] = anychart.elements.TextMarker.prototype.text;
anychart.elements.TextMarker.prototype['height'] = anychart.elements.TextMarker.prototype.height;
anychart.elements.TextMarker.prototype['width'] = anychart.elements.TextMarker.prototype.width;
anychart.elements.TextMarker.prototype['draw'] = anychart.elements.TextMarker.prototype.draw;
anychart.elements.TextMarker.prototype['isHorizontal'] = anychart.elements.TextMarker.prototype.isHorizontal;
goog.exportSymbol('anychart.elements.TextMarker.Align.CENTER', anychart.elements.TextMarker.Align.CENTER);
goog.exportSymbol('anychart.elements.TextMarker.Align.NEAR', anychart.elements.TextMarker.Align.NEAR);
goog.exportSymbol('anychart.elements.TextMarker.Align.FAR', anychart.elements.TextMarker.Align.FAR);
