goog.provide('anychart.exports.ElementsMultilabel');
goog.require('anychart.elements.Multilabel');

goog.exportSymbol('anychart.elements.Multilabel', anychart.elements.Multilabel);
anychart.elements.Multilabel.prototype['background'] = anychart.elements.Multilabel.prototype.background;
anychart.elements.Multilabel.prototype['backgroundAt'] = anychart.elements.Multilabel.prototype.backgroundAt;
anychart.elements.Multilabel.prototype['textFormatter'] = anychart.elements.Multilabel.prototype.textFormatter;
anychart.elements.Multilabel.prototype['positionFormatter'] = anychart.elements.Multilabel.prototype.positionFormatter;
anychart.elements.Multilabel.prototype['position'] = anychart.elements.Multilabel.prototype.position;
anychart.elements.Multilabel.prototype['positionAt'] = anychart.elements.Multilabel.prototype.positionAt;
anychart.elements.Multilabel.prototype['anchor'] = anychart.elements.Multilabel.prototype.anchor;
anychart.elements.Multilabel.prototype['anchorAt'] = anychart.elements.Multilabel.prototype.anchorAt;
anychart.elements.Multilabel.prototype['offsetX'] = anychart.elements.Multilabel.prototype.offsetX;
anychart.elements.Multilabel.prototype['offsetXAt'] = anychart.elements.Multilabel.prototype.offsetXAt;
anychart.elements.Multilabel.prototype['offsetY'] = anychart.elements.Multilabel.prototype.offsetY;
anychart.elements.Multilabel.prototype['offsetYAt'] = anychart.elements.Multilabel.prototype.offsetYAt;
anychart.elements.Multilabel.prototype['width'] = anychart.elements.Multilabel.prototype.width;
anychart.elements.Multilabel.prototype['widthAt'] = anychart.elements.Multilabel.prototype.widthAt;
anychart.elements.Multilabel.prototype['height'] = anychart.elements.Multilabel.prototype.height;
anychart.elements.Multilabel.prototype['heightAt'] = anychart.elements.Multilabel.prototype.heightAt;
anychart.elements.Multilabel.prototype['enabledAt'] = anychart.elements.Multilabel.prototype.enabledAt;
anychart.elements.Multilabel.prototype['textSettingsAt'] = anychart.elements.Multilabel.prototype.textSettingsAt;
anychart.elements.Multilabel.prototype['serializeAt'] = anychart.elements.Multilabel.prototype.serializeAt;
anychart.elements.Multilabel.prototype['deserializeAt'] = anychart.elements.Multilabel.prototype.deserializeAt;
anychart.elements.Multilabel.prototype['serialize'] = anychart.elements.Multilabel.prototype.serialize;
anychart.elements.Multilabel.prototype['deserialize'] = anychart.elements.Multilabel.prototype.deserialize;
anychart.elements.Multilabel.prototype['end'] = anychart.elements.Multilabel.prototype.end;
anychart.elements.Multilabel.prototype['draw'] = anychart.elements.Multilabel.prototype.draw;
