goog.provide('anychart.exports.ElementsLegend');
goog.require('anychart.elements.Legend');

goog.exportSymbol('anychart.elements.Legend', anychart.elements.Legend);
anychart.elements.Legend.prototype['itemsLayout'] = anychart.elements.Legend.prototype.itemsLayout;
anychart.elements.Legend.prototype['itemsProvider'] = anychart.elements.Legend.prototype.itemsProvider;
anychart.elements.Legend.prototype['itemsSpacing'] = anychart.elements.Legend.prototype.itemsSpacing;
anychart.elements.Legend.prototype['iconTextSpacing'] = anychart.elements.Legend.prototype.iconTextSpacing;
anychart.elements.Legend.prototype['margin'] = anychart.elements.Legend.prototype.margin;
anychart.elements.Legend.prototype['padding'] = anychart.elements.Legend.prototype.padding;
anychart.elements.Legend.prototype['background'] = anychart.elements.Legend.prototype.background;
anychart.elements.Legend.prototype['title'] = anychart.elements.Legend.prototype.title;
anychart.elements.Legend.prototype['titleSeparator'] = anychart.elements.Legend.prototype.titleSeparator;
anychart.elements.Legend.prototype['paginator'] = anychart.elements.Legend.prototype.paginator;
anychart.elements.Legend.prototype['width'] = anychart.elements.Legend.prototype.width;
anychart.elements.Legend.prototype['height'] = anychart.elements.Legend.prototype.height;
anychart.elements.Legend.prototype['parentBounds'] = anychart.elements.Legend.prototype.parentBounds;
anychart.elements.Legend.prototype['position'] = anychart.elements.Legend.prototype.position;
anychart.elements.Legend.prototype['align'] = anychart.elements.Legend.prototype.align;
anychart.elements.Legend.prototype['getRemainingBounds'] = anychart.elements.Legend.prototype.getRemainingBounds;
anychart.elements.Legend.prototype['draw'] = anychart.elements.Legend.prototype.draw;
