goog.provide('anychart.exports.ElementsTooltip');
goog.require('anychart.elements.Tooltip');

goog.exportSymbol('anychart.elements.Tooltip', anychart.elements.Tooltip);
anychart.elements.Tooltip.prototype['titleFormatter'] = anychart.elements.Tooltip.prototype.titleFormatter;
anychart.elements.Tooltip.prototype['textFormatter'] = anychart.elements.Tooltip.prototype.textFormatter;
anychart.elements.Tooltip.prototype['allowLeaveScreen'] = anychart.elements.Tooltip.prototype.allowLeaveScreen;
anychart.elements.Tooltip.prototype['isFloating'] = anychart.elements.Tooltip.prototype.isFloating;
anychart.elements.Tooltip.prototype['title'] = anychart.elements.Tooltip.prototype.title;
anychart.elements.Tooltip.prototype['separator'] = anychart.elements.Tooltip.prototype.separator;
anychart.elements.Tooltip.prototype['content'] = anychart.elements.Tooltip.prototype.content;
anychart.elements.Tooltip.prototype['background'] = anychart.elements.Tooltip.prototype.background;
anychart.elements.Tooltip.prototype['padding'] = anychart.elements.Tooltip.prototype.padding;
anychart.elements.Tooltip.prototype['offsetX'] = anychart.elements.Tooltip.prototype.offsetX;
anychart.elements.Tooltip.prototype['offsetY'] = anychart.elements.Tooltip.prototype.offsetY;
anychart.elements.Tooltip.prototype['anchor'] = anychart.elements.Tooltip.prototype.anchor;
anychart.elements.Tooltip.prototype['hideDelay'] = anychart.elements.Tooltip.prototype.hideDelay;
anychart.elements.Tooltip.prototype['show'] = anychart.elements.Tooltip.prototype.show;
anychart.elements.Tooltip.prototype['hide'] = anychart.elements.Tooltip.prototype.hide;
anychart.elements.Tooltip.prototype['redraw'] = anychart.elements.Tooltip.prototype.redraw;
anychart.elements.Tooltip.prototype['enabled'] = anychart.elements.Tooltip.prototype.enabled;
