goog.provide('anychart.exports.ElementsAxis');
goog.require('anychart.elements.Axis');

goog.exportSymbol('anychart.elements.Axis', anychart.elements.Axis);
anychart.elements.Axis.prototype['title'] = anychart.elements.Axis.prototype.title;
anychart.elements.Axis.prototype['name'] = anychart.elements.Axis.prototype.name;
anychart.elements.Axis.prototype['labels'] = anychart.elements.Axis.prototype.labels;
anychart.elements.Axis.prototype['minorLabels'] = anychart.elements.Axis.prototype.minorLabels;
anychart.elements.Axis.prototype['ticks'] = anychart.elements.Axis.prototype.ticks;
anychart.elements.Axis.prototype['minorTicks'] = anychart.elements.Axis.prototype.minorTicks;
anychart.elements.Axis.prototype['stroke'] = anychart.elements.Axis.prototype.stroke;
anychart.elements.Axis.prototype['orientation'] = anychart.elements.Axis.prototype.orientation;
anychart.elements.Axis.prototype['scale'] = anychart.elements.Axis.prototype.scale;
anychart.elements.Axis.prototype['offsetX'] = anychart.elements.Axis.prototype.offsetX;
anychart.elements.Axis.prototype['offsetY'] = anychart.elements.Axis.prototype.offsetY;
anychart.elements.Axis.prototype['length'] = anychart.elements.Axis.prototype.length;
anychart.elements.Axis.prototype['parentBounds'] = anychart.elements.Axis.prototype.parentBounds;
anychart.elements.Axis.prototype['getRemainingBounds'] = anychart.elements.Axis.prototype.getRemainingBounds;
anychart.elements.Axis.prototype['drawFirstLabel'] = anychart.elements.Axis.prototype.drawFirstLabel;
anychart.elements.Axis.prototype['drawLastLabel'] = anychart.elements.Axis.prototype.drawLastLabel;
anychart.elements.Axis.prototype['overlapMode'] = anychart.elements.Axis.prototype.overlapMode;
anychart.elements.Axis.prototype['isHorizontal'] = anychart.elements.Axis.prototype.isHorizontal;
anychart.elements.Axis.prototype['draw'] = anychart.elements.Axis.prototype.draw;
anychart.elements.Axis.prototype['serialize'] = anychart.elements.Axis.prototype.serialize;
anychart.elements.Axis.prototype['deserialize'] = anychart.elements.Axis.prototype.deserialize;
